<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" /></ItemGroup><ItemGroup><ProjectReference Include="../../src/Modules/Procurement/CommerceOS.Procurement.Application/CommerceOS.Procurement.Application.csproj" /><ProjectReference Include="../../src/Modules/Procurement/CommerceOS.Procurement.Domain/CommerceOS.Procurement.Domain.csproj" /></ItemGroup></Project>
