<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" /></ItemGroup><ItemGroup><ProjectReference Include="../../src/Modules/Inventory/CommerceOS.Inventory.Application/CommerceOS.Inventory.Application.csproj" /><ProjectReference Include="../../src/Modules/Inventory/CommerceOS.Inventory.Domain/CommerceOS.Inventory.Domain.csproj" /><ProjectReference Include="../../src/Modules/SubscriptionBilling/CommerceOS.SubscriptionBilling.Contracts/CommerceOS.SubscriptionBilling.Contracts.csproj" /></ItemGroup></Project>
