using System.Globalization;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using CommerceOS.Procurement.Application;
using CommerceOS.Procurement.Domain;

namespace CommerceOS.Procurement.Infrastructure.Persistence;

public sealed record DynamoDbProcurementOptions(string TableName);
public sealed class DynamoDbProcurementStore(IAmazonDynamoDB client, DynamoDbProcurementOptions options) : IProcurementStore, IGoodsReceiptStore
{
    public async Task<Supplier?> GetSupplierAsync(TrustedProcurementMutationContext context, SupplierId id, CancellationToken cancellationToken)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"SUPPLIER#{E(id.Value)}") }, cancellationToken); return item.Item.Count == 0 ? null : new(new(item.Item["SupplierId"].S), new(item.Item["TenantId"].S), item.Item["Name"].S, Enum.Parse<SupplierStatus>(item.Item["Status"].S), long.Parse(item.Item["Revision"].N, CultureInfo.InvariantCulture)); }
    public async Task<ProcurementOutcome> SaveSupplierAsync(TrustedProcurementMutationContext context, Supplier supplier, long? expectedRevision, CancellationToken cancellationToken)
    { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = new() { ["PK"] = S(P(supplier.TenantId)), ["SK"] = S($"SUPPLIER#{E(supplier.Id.Value)}"), ["SupplierId"] = S(supplier.Id.Value), ["TenantId"] = S(supplier.TenantId.Value), ["Name"] = S(supplier.DisplayName), ["Status"] = S(supplier.Status.ToString()), ["Revision"] = N(supplier.Revision) }, ConditionExpression = expectedRevision is null ? "attribute_not_exists(PK)" : "Revision = :revision", ExpressionAttributeValues = expectedRevision is null ? null : new() { [":revision"] = N(expectedRevision.Value) } }, cancellationToken); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.RevisionConflict; } }
    public async Task<PurchaseOrder?> GetPurchaseOrderAsync(TrustedProcurementMutationContext context, PurchaseOrderId id, CancellationToken cancellationToken)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"PO#{E(id.Value)}") }, cancellationToken); return item.Item.Count == 0 ? null : ReadOrder(item.Item); }
    public async Task<ProcurementOutcome> SavePurchaseOrderAsync(TrustedProcurementMutationContext context, PurchaseOrder order, long? expectedRevision, CancellationToken cancellationToken)
    { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = OrderItem(order), ConditionExpression = expectedRevision is null ? "attribute_not_exists(PK)" : "Revision = :revision", ExpressionAttributeValues = expectedRevision is null ? null : new() { [":revision"] = N(expectedRevision.Value) } }, cancellationToken); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.RevisionConflict; } }
    public async Task<GoodsReceipt?> GetAsync(TrustedProcurementMutationContext context, string id, CancellationToken ct)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"RECEIPT#{E(id)}") }, ct); return item.Item.Count == 0 ? null : ReadReceipt(item.Item); }
    public async Task<IReadOnlyList<GoodsReceiptCorrection>> ListCorrectionsAsync(TrustedProcurementMutationContext context, string receiptId, CancellationToken ct)
    { var result = await client.QueryAsync(new() { TableName = options.TableName, KeyConditionExpression = "PK = :pk AND begins_with(SK, :prefix)", ExpressionAttributeValues = new() { [":pk"] = S(P(context.TenantId)), [":prefix"] = S($"CORRECTION#{E(receiptId)}#") } }, ct); return result.Items.Select(ReadCorrection).ToArray(); }
    public async Task<ProcurementOutcome> ConfirmAsync(TrustedProcurementMutationContext context, GoodsReceipt receipt, string sourceIdentity, CancellationToken ct)
    { if (receipt.TenantId != context.TenantId) return ProcurementOutcome.NotFound; try { await client.PutItemAsync(new() { TableName = options.TableName, Item = ReceiptItem(receipt, sourceIdentity), ConditionExpression = "Revision = :revision", ExpressionAttributeValues = new() { [":revision"] = N(receipt.Revision - 1) } }, ct); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.Immutable; } }
    public async Task<ProcurementOutcome> RecordCorrectionAsync(TrustedProcurementMutationContext context, GoodsReceiptCorrection correction, CancellationToken ct)
    { if (correction.TenantId != context.TenantId) return ProcurementOutcome.NotFound; try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = CorrectionItem(correction), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Put = new() { TableName = options.TableName, Item = new() { ["PK"] = S(P(context.TenantId)), ["SK"] = S($"CORRECTION-SOURCE#{E(correction.SourceIdentity)}"), ["CorrectionId"] = S(correction.Id) }, ConditionExpression = "attribute_not_exists(PK)" } }] }, ct); return ProcurementOutcome.Applied; } catch (TransactionCanceledException) { return ProcurementOutcome.Immutable; } }
    private static PurchaseOrder ReadOrder(Dictionary<string, AttributeValue> item) => new(new(item["PurchaseOrderId"].S), new(item["TenantId"].S), new(item["SupplierId"].S), item["Lines"].L.Select(x => new PurchaseOrderLine(x.M["ProductId"].S, x.M["ProductName"].S, x.M.TryGetValue("Sku", out var sku) ? sku.S : null, long.Parse(x.M["Quantity"].N, CultureInfo.InvariantCulture), long.Parse(x.M["UnitPriceVnd"].N, CultureInfo.InvariantCulture))).ToArray(), Enum.Parse<PurchaseOrderStatus>(item["Status"].S), long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceipt ReadReceipt(Dictionary<string, AttributeValue> item) => new(item["ReceiptId"].S, new(item["PurchaseOrderId"].S), new(item["TenantId"].S), ReadReceiptLines(item), Enum.Parse<GoodsReceiptStatus>(item["Status"].S), item.TryGetValue("CorrectsReceiptId", out var corrects) ? corrects.S : null, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceiptCorrection ReadCorrection(Dictionary<string, AttributeValue> item) => new(item["CorrectionId"].S, item["ReceiptId"].S, new(item["TenantId"].S), ReadReceiptLines(item), item["SourceIdentity"].S, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceiptLine[] ReadReceiptLines(Dictionary<string, AttributeValue> item) => item["Lines"].L.Select(x => new GoodsReceiptLine(x.M["ProductId"].S, long.Parse(x.M["Quantity"].N, CultureInfo.InvariantCulture))).ToArray();
    private static Dictionary<string, AttributeValue> OrderItem(PurchaseOrder x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"PO#{E(x.Id.Value)}"), ["PurchaseOrderId"] = S(x.Id.Value), ["TenantId"] = S(x.TenantId.Value), ["SupplierId"] = S(x.SupplierId.Value), ["Status"] = S(x.Status.ToString()), ["Revision"] = N(x.Revision), ["Lines"] = new() { L = x.Lines.Select(line => new AttributeValue { M = new() { ["ProductId"] = S(line.ProductId), ["ProductName"] = S(line.ProductNameSnapshot), ["Quantity"] = N(line.Quantity), ["UnitPriceVnd"] = N(line.UnitPriceVnd) } }).ToList() } };
    private static Dictionary<string, AttributeValue> ReceiptItem(GoodsReceipt x, string sourceIdentity) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"RECEIPT#{E(x.Id)}"), ["ReceiptId"] = S(x.Id), ["PurchaseOrderId"] = S(x.PurchaseOrderId.Value), ["TenantId"] = S(x.TenantId.Value), ["Status"] = S(x.Status.ToString()), ["SourceIdentity"] = S(sourceIdentity), ["Revision"] = N(x.Revision), ["Lines"] = ReceiptLines(x.Lines) };
    private static Dictionary<string, AttributeValue> CorrectionItem(GoodsReceiptCorrection x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"CORRECTION#{E(x.ReceiptId)}#{E(x.Id)}"), ["CorrectionId"] = S(x.Id), ["ReceiptId"] = S(x.ReceiptId), ["TenantId"] = S(x.TenantId.Value), ["SourceIdentity"] = S(x.SourceIdentity), ["Revision"] = N(x.Revision), ["Lines"] = ReceiptLines(x.Lines) };
    private static AttributeValue ReceiptLines(IReadOnlyList<GoodsReceiptLine> lines) => new() { L = lines.Select(line => new AttributeValue { M = new() { ["ProductId"] = S(line.ProductId), ["Quantity"] = N(line.Quantity) } }).ToList() };
    private static Dictionary<string, AttributeValue> Key(ProcurementTenantId t, string sk) => new() { ["PK"] = S(P(t)), ["SK"] = S(sk) }; private static string P(ProcurementTenantId t) => $"TENANT#{E(t.Value)}"; private static string E(string x) => Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(x)).TrimEnd('=').Replace('+', '-').Replace('/', '_'); private static AttributeValue S(string x) => new() { S = x }; private static AttributeValue N(long x) => new() { N = x.ToString(CultureInfo.InvariantCulture) };
}
