using System.Globalization;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using CommerceOS.Procurement.Application;
using CommerceOS.Procurement.Domain;

namespace CommerceOS.Procurement.Infrastructure.Persistence;

public sealed record DynamoDbProcurementOptions(string TableName);
public sealed class DynamoDbProcurementStore(IAmazonDynamoDB client, DynamoDbProcurementOptions options) : IProcurementStore, IGoodsReceiptStore, ISupplierInvoiceStore
{
    public async Task<Supplier?> GetSupplierAsync(TrustedProcurementMutationContext context, SupplierId id, CancellationToken cancellationToken)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"SUPPLIER#{E(id.Value)}") }, cancellationToken); return item.Item.Count == 0 ? null : new(new(item.Item["SupplierId"].S), new(item.Item["TenantId"].S), item.Item["Name"].S, Enum.Parse<SupplierStatus>(item.Item["Status"].S), long.Parse(item.Item["Revision"].N, CultureInfo.InvariantCulture)); }
    public async Task<IReadOnlyList<Supplier>> ListSuppliersAsync(TrustedProcurementMutationContext context, CancellationToken cancellationToken) { var response = await QueryAsync(context, "SUPPLIER#", cancellationToken); return response.Select(ReadSupplier).OrderBy(x => x.DisplayName, StringComparer.OrdinalIgnoreCase).ToArray(); }
    public async Task<ProcurementOutcome> SaveSupplierAsync(TrustedProcurementMutationContext context, Supplier supplier, long? expectedRevision, CancellationToken cancellationToken)
    { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = new() { ["PK"] = S(P(supplier.TenantId)), ["SK"] = S($"SUPPLIER#{E(supplier.Id.Value)}"), ["SupplierId"] = S(supplier.Id.Value), ["TenantId"] = S(supplier.TenantId.Value), ["Name"] = S(supplier.DisplayName), ["Status"] = S(supplier.Status.ToString()), ["Revision"] = N(supplier.Revision) }, ConditionExpression = expectedRevision is null ? "attribute_not_exists(PK)" : "Revision = :revision", ExpressionAttributeValues = expectedRevision is null ? null : new() { [":revision"] = N(expectedRevision.Value) } }, cancellationToken); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.RevisionConflict; } }
    public async Task<PurchaseOrder?> GetPurchaseOrderAsync(TrustedProcurementMutationContext context, PurchaseOrderId id, CancellationToken cancellationToken)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"PO#{E(id.Value)}") }, cancellationToken); return item.Item.Count == 0 ? null : ReadOrder(item.Item); }
    public async Task<IReadOnlyList<PurchaseOrder>> ListPurchaseOrdersAsync(TrustedProcurementMutationContext context, CancellationToken cancellationToken) => (await QueryAsync(context, "PO#", cancellationToken)).Select(ReadOrder).ToArray();
    public async Task<ProcurementOutcome> SavePurchaseOrderAsync(TrustedProcurementMutationContext context, PurchaseOrder order, long? expectedRevision, CancellationToken cancellationToken)
    { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = OrderItem(order), ConditionExpression = expectedRevision is null ? "attribute_not_exists(PK)" : "Revision = :revision", ExpressionAttributeValues = expectedRevision is null ? null : new() { [":revision"] = N(expectedRevision.Value) } }, cancellationToken); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.RevisionConflict; } }
    public async Task<GoodsReceipt?> GetAsync(TrustedProcurementMutationContext context, string id, CancellationToken ct)
    { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"RECEIPT#{E(id)}") }, ct); return item.Item.Count == 0 ? null : ReadReceipt(item.Item); }
    public async Task<IReadOnlyList<GoodsReceipt>> ListAsync(TrustedProcurementMutationContext context, PurchaseOrderId? purchaseOrderId, CancellationToken ct) => (await QueryAsync(context, "RECEIPT#", ct)).Select(ReadReceipt).Where(x => purchaseOrderId is null || x.PurchaseOrderId == purchaseOrderId.Value).ToArray();
    public async Task<ProcurementOutcome> CreateAsync(TrustedProcurementMutationContext context, GoodsReceipt receipt, CancellationToken ct) { if (receipt.TenantId != context.TenantId) return ProcurementOutcome.NotFound; try { await client.PutItemAsync(new() { TableName = options.TableName, Item = ReceiptItem(receipt, "draft"), ConditionExpression = "attribute_not_exists(PK)" }, ct); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.RevisionConflict; } }
    public async Task<IReadOnlyList<GoodsReceiptCorrection>> ListCorrectionsAsync(TrustedProcurementMutationContext context, string receiptId, CancellationToken ct)
    { var result = await client.QueryAsync(new() { TableName = options.TableName, KeyConditionExpression = "PK = :pk AND begins_with(SK, :prefix)", ExpressionAttributeValues = new() { [":pk"] = S(P(context.TenantId)), [":prefix"] = S($"CORRECTION#{E(receiptId)}#") } }, ct); return result.Items.Select(ReadCorrection).ToArray(); }
    public async Task<ProcurementOutcome> ConfirmAsync(TrustedProcurementMutationContext context, GoodsReceipt receipt, string sourceIdentity, CancellationToken ct)
    { if (receipt.TenantId != context.TenantId) return ProcurementOutcome.NotFound; try { await client.PutItemAsync(new() { TableName = options.TableName, Item = ReceiptItem(receipt, sourceIdentity), ConditionExpression = "Revision = :revision", ExpressionAttributeValues = new() { [":revision"] = N(receipt.Revision - 1) } }, ct); return ProcurementOutcome.Applied; } catch (ConditionalCheckFailedException) { return ProcurementOutcome.Immutable; } }
    public async Task<ProcurementOutcome> RecordCorrectionAsync(TrustedProcurementMutationContext context, GoodsReceiptCorrection correction, CancellationToken ct)
    { if (correction.TenantId != context.TenantId) return ProcurementOutcome.NotFound; try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = CorrectionItem(correction), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Put = new() { TableName = options.TableName, Item = new() { ["PK"] = S(P(context.TenantId)), ["SK"] = S($"CORRECTION-SOURCE#{E(correction.SourceIdentity)}"), ["CorrectionId"] = S(correction.Id) }, ConditionExpression = "attribute_not_exists(PK)" } }] }, ct); return ProcurementOutcome.Applied; } catch (TransactionCanceledException) { return ProcurementOutcome.Immutable; } }
    public async Task<IReadOnlyList<SupplierInvoice>> ListInvoicesAsync(TrustedProcurementMutationContext context, CancellationToken ct) => (await QueryAsync(context, "INVOICE#", ct)).Select(ReadInvoice).ToArray();
    public async Task<IReadOnlyList<SupplierPayment>> ListPaymentsAsync(TrustedProcurementMutationContext context, string? invoiceId, CancellationToken ct) => (await QueryAsync(context, "PAYMENT#", ct)).Select(ReadPayment).Where(x => string.IsNullOrWhiteSpace(invoiceId) || x.SupplierInvoiceId == invoiceId).ToArray();
    public async Task<bool> IsFullyReceivedAsync(TrustedProcurementMutationContext context, PurchaseOrderId id, CancellationToken ct)
    { var order = await GetPurchaseOrderAsync(context, id, ct); if (order is null) return false; var receipts = await ListAsync(context, id, ct); var received = new Dictionary<string, long>(); foreach (var receipt in receipts.Where(x => x.Status is GoodsReceiptStatus.Confirmed)) foreach (var line in receipt.Lines) received[line.ProductId] = received.GetValueOrDefault(line.ProductId) + line.Quantity; foreach (var receipt in receipts.Where(x => x.Status is GoodsReceiptStatus.Confirmed)) foreach (var correction in await ListCorrectionsAsync(context, receipt.Id, ct)) foreach (var line in correction.Lines) received[line.ProductId] = received.GetValueOrDefault(line.ProductId) - line.Quantity; return order.Lines.All(line => received.GetValueOrDefault(line.ProductId) >= line.Quantity); }
    public async Task<SupplierInvoice?> GetInvoiceForPurchaseOrderAsync(TrustedProcurementMutationContext context, PurchaseOrderId id, CancellationToken ct) => (await ListInvoicesAsync(context, ct)).SingleOrDefault(x => x.PurchaseOrderId == id);
    public async Task<SupplierInvoice?> GetInvoiceAsync(TrustedProcurementMutationContext context, string id, CancellationToken ct) { var item = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(context.TenantId, $"INVOICE#{E(id)}") }, ct); return item.Item.Count == 0 ? null : ReadInvoice(item.Item); }
    public async Task<SupplierInvoiceOutcome> CreateInvoiceAsync(TrustedProcurementMutationContext context, SupplierInvoice invoice, CancellationToken ct) { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = InvoiceItem(invoice), ConditionExpression = "attribute_not_exists(PK)" }, ct); return SupplierInvoiceOutcome.Applied; } catch (ConditionalCheckFailedException) { return SupplierInvoiceOutcome.InvoiceConflict; } }
    public async Task<SupplierInvoiceOutcome> SaveInvoiceAsync(TrustedProcurementMutationContext context, SupplierInvoice before, SupplierInvoice after, CancellationToken ct) { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = InvoiceItem(after), ConditionExpression = "Revision = :revision", ExpressionAttributeValues = new() { [":revision"] = N(before.Revision) } }, ct); return SupplierInvoiceOutcome.Applied; } catch (ConditionalCheckFailedException) { return SupplierInvoiceOutcome.InvoiceConflict; } }
    public async Task<SupplierInvoiceOutcome> RecordPaymentAsync(TrustedProcurementMutationContext context, SupplierPayment payment, CancellationToken ct) { try { await client.PutItemAsync(new() { TableName = options.TableName, Item = PaymentItem(payment), ConditionExpression = "attribute_not_exists(PK)" }, ct); return SupplierInvoiceOutcome.Applied; } catch (ConditionalCheckFailedException) { return SupplierInvoiceOutcome.AlreadyApplied; } }
    private static Supplier ReadSupplier(Dictionary<string, AttributeValue> item) => new(new(item["SupplierId"].S), new(item["TenantId"].S), item["Name"].S, Enum.Parse<SupplierStatus>(item["Status"].S), long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static PurchaseOrder ReadOrder(Dictionary<string, AttributeValue> item) => new(new(item["PurchaseOrderId"].S), new(item["TenantId"].S), new(item["SupplierId"].S), item["Lines"].L.Select(x => new PurchaseOrderLine(x.M["ProductId"].S, x.M["ProductName"].S, x.M.TryGetValue("Sku", out var sku) ? sku.S : null, long.Parse(x.M["Quantity"].N, CultureInfo.InvariantCulture), long.Parse(x.M["UnitPriceVnd"].N, CultureInfo.InvariantCulture))).ToArray(), Enum.Parse<PurchaseOrderStatus>(item["Status"].S), long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceipt ReadReceipt(Dictionary<string, AttributeValue> item) => new(item["ReceiptId"].S, new(item["PurchaseOrderId"].S), new(item["TenantId"].S), ReadReceiptLines(item), Enum.Parse<GoodsReceiptStatus>(item["Status"].S), item.TryGetValue("CorrectsReceiptId", out var corrects) ? corrects.S : null, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceiptCorrection ReadCorrection(Dictionary<string, AttributeValue> item) => new(item["CorrectionId"].S, item["ReceiptId"].S, new(item["TenantId"].S), ReadReceiptLines(item), item["SourceIdentity"].S, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static GoodsReceiptLine[] ReadReceiptLines(Dictionary<string, AttributeValue> item) => item["Lines"].L.Select(x => new GoodsReceiptLine(x.M["ProductId"].S, long.Parse(x.M["Quantity"].N, CultureInfo.InvariantCulture), x.M.TryGetValue("WarehouseId", out var warehouse) ? warehouse.S : null)).ToArray();
    private static Dictionary<string, AttributeValue> OrderItem(PurchaseOrder x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"PO#{E(x.Id.Value)}"), ["PurchaseOrderId"] = S(x.Id.Value), ["TenantId"] = S(x.TenantId.Value), ["SupplierId"] = S(x.SupplierId.Value), ["Status"] = S(x.Status.ToString()), ["Revision"] = N(x.Revision), ["Lines"] = new() { L = x.Lines.Select(line => new AttributeValue { M = new Dictionary<string, AttributeValue> { ["ProductId"] = S(line.ProductId), ["ProductName"] = S(line.ProductNameSnapshot), ["Quantity"] = N(line.Quantity), ["UnitPriceVnd"] = N(line.UnitPriceVnd) }.WithSku(line.SkuSnapshot) }).ToList() } };
    private static Dictionary<string, AttributeValue> ReceiptItem(GoodsReceipt x, string sourceIdentity) => new Dictionary<string, AttributeValue> { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"RECEIPT#{E(x.Id)}"), ["ReceiptId"] = S(x.Id), ["PurchaseOrderId"] = S(x.PurchaseOrderId.Value), ["TenantId"] = S(x.TenantId.Value), ["Status"] = S(x.Status.ToString()), ["SourceIdentity"] = S(sourceIdentity), ["Revision"] = N(x.Revision), ["Lines"] = ReceiptLines(x.Lines) }.WithCorrectsReceipt(x.CorrectsReceiptId);
    private static Dictionary<string, AttributeValue> CorrectionItem(GoodsReceiptCorrection x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"CORRECTION#{E(x.ReceiptId)}#{E(x.Id)}"), ["CorrectionId"] = S(x.Id), ["ReceiptId"] = S(x.ReceiptId), ["TenantId"] = S(x.TenantId.Value), ["SourceIdentity"] = S(x.SourceIdentity), ["Revision"] = N(x.Revision), ["Lines"] = ReceiptLines(x.Lines) };
    private static SupplierInvoice ReadInvoice(Dictionary<string, AttributeValue> item) => new(item["InvoiceId"].S, new(item["PurchaseOrderId"].S), new(item["TenantId"].S), item["SupplierReference"].S, DateOnly.Parse(item["InvoiceDate"].S, CultureInfo.InvariantCulture), long.Parse(item["AmountVnd"].N, CultureInfo.InvariantCulture), Enum.Parse<SupplierInvoiceStatus>(item["Status"].S), long.Parse(item["ExpectedAmountVnd"].N, CultureInfo.InvariantCulture), item["SourceIdentity"].S, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static SupplierPayment ReadPayment(Dictionary<string, AttributeValue> item) => new(item["PaymentId"].S, item["SupplierInvoiceId"].S, new(item["TenantId"].S), item["ExternalReference"].S, DateOnly.Parse(item["PaidOn"].S, CultureInfo.InvariantCulture), long.Parse(item["AmountVnd"].N, CultureInfo.InvariantCulture), item["SourceIdentity"].S, long.Parse(item["Revision"].N, CultureInfo.InvariantCulture));
    private static Dictionary<string, AttributeValue> InvoiceItem(SupplierInvoice x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"INVOICE#{E(x.Id)}"), ["InvoiceId"] = S(x.Id), ["PurchaseOrderId"] = S(x.PurchaseOrderId.Value), ["TenantId"] = S(x.TenantId.Value), ["SupplierReference"] = S(x.SupplierReference), ["InvoiceDate"] = S(x.InvoiceDate.ToString("O", CultureInfo.InvariantCulture)), ["AmountVnd"] = N(x.AmountVnd), ["Status"] = S(x.Status.ToString()), ["ExpectedAmountVnd"] = N(x.ExpectedAmountVnd), ["SourceIdentity"] = S(x.SourceIdentity), ["Revision"] = N(x.Revision) };
    private static Dictionary<string, AttributeValue> PaymentItem(SupplierPayment x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"PAYMENT#{E(x.Id)}"), ["PaymentId"] = S(x.Id), ["SupplierInvoiceId"] = S(x.SupplierInvoiceId), ["TenantId"] = S(x.TenantId.Value), ["ExternalReference"] = S(x.ExternalReference), ["PaidOn"] = S(x.PaidOn.ToString("O", CultureInfo.InvariantCulture)), ["AmountVnd"] = N(x.AmountVnd), ["SourceIdentity"] = S(x.SourceIdentity), ["Revision"] = N(x.Revision) };
    private static AttributeValue ReceiptLines(IReadOnlyList<GoodsReceiptLine> lines) => new() { L = lines.Select(line => new AttributeValue { M = new Dictionary<string, AttributeValue> { ["ProductId"] = S(line.ProductId), ["Quantity"] = N(line.Quantity) }.WithWarehouse(line.WarehouseId) }).ToList() };
    private async Task<IReadOnlyList<Dictionary<string, AttributeValue>>> QueryAsync(TrustedProcurementMutationContext context, string prefix, CancellationToken ct) { var response = await client.QueryAsync(new() { TableName = options.TableName, KeyConditionExpression = "PK = :pk AND begins_with(SK, :prefix)", ExpressionAttributeValues = new() { [":pk"] = S(P(context.TenantId)), [":prefix"] = S(prefix) } }, ct); return response.Items; }
    private static Dictionary<string, AttributeValue> Key(ProcurementTenantId t, string sk) => new() { ["PK"] = S(P(t)), ["SK"] = S(sk) }; private static string P(ProcurementTenantId t) => $"TENANT#{E(t.Value)}"; private static string E(string x) => Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(x)).TrimEnd('=').Replace('+', '-').Replace('/', '_'); private static AttributeValue S(string x) => new() { S = x }; private static AttributeValue N(long x) => new() { N = x.ToString(CultureInfo.InvariantCulture) };
}

internal static class ProcurementAttributeExtensions
{
    public static Dictionary<string, AttributeValue> WithWarehouse(this Dictionary<string, AttributeValue> item, string? warehouseId) { if (!string.IsNullOrWhiteSpace(warehouseId)) item["WarehouseId"] = new() { S = warehouseId }; return item; }
    public static Dictionary<string, AttributeValue> WithSku(this Dictionary<string, AttributeValue> item, string? sku) { if (!string.IsNullOrWhiteSpace(sku)) item["Sku"] = new() { S = sku }; return item; }
    public static Dictionary<string, AttributeValue> WithCorrectsReceipt(this Dictionary<string, AttributeValue> item, string? receiptId) { if (!string.IsNullOrWhiteSpace(receiptId)) item["CorrectsReceiptId"] = new() { S = receiptId }; return item; }
}
