import { useEffect, useState } from 'react'
import { AlertPanel, AppLink, AppShell, FormField, PageState, Router, StatusBadge, createApiClient, type RouteDefinition } from '@commerceos/frontend-foundation'
const api = createApiClient(import.meta.env.VITE_COMMERCEOS_API_BASE_URL ?? '')
interface Tenant { id: { value: string } | string; status: string; profile: { displayName: string; timeZoneIana: string }; revision: number }
interface Health { status: string; service: string }
const id = (value: { value: string } | string) => typeof value === 'string' ? value : value.value
function Shell({ children }: { children: React.ReactNode }) { return <AppShell brand="CommerceOS Platform" navigation={[{ label: 'Tổng quan', href: '/platform' }, { label: 'Doanh nghiệp', href: '/platform/tenants' }]}>{children}</AppShell> }
function Dashboard() { const [health,setHealth]=useState<Health>();const [error,setError]=useState<unknown>();useEffect(()=>{void api.request<Health>('/api/v1/platform/health').then(setHealth).catch(setError)},[]);return <Shell><main className="page"><h1>Platform Admin</h1><p className="notice">Không dùng merchant session: Platform Admin yêu cầu một authority riêng.</p>{error!==undefined?<AlertPanel error={error}/>:!health?<PageState kind="loading"/>:<section className="section"><h2>Readiness</h2><p>{health.service}: <StatusBadge tone={health.status==='ok'?'success':'warning'}>{health.status}</StatusBadge></p></section>}</main></Shell> }
function Tenants() { const [items,setItems]=useState<Tenant[]>([]);const [search,setSearch]=useState('');const [error,setError]=useState<unknown>();const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setItems(await api.request<Tenant[]>(`/api/v1/platform/tenants${search?`?search=${encodeURIComponent(search)}`:''}`));setError(undefined)}catch(e){setError(e)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);return <Shell><main className="page"><h1>Hỗ trợ doanh nghiệp</h1><form className="actions" onSubmit={e=>{e.preventDefault();void load()}}><FormField label="Tìm kiếm"><input value={search} onChange={e=>setSearch(e.target.value)}/></FormField><button className="co-button co-button-secondary" type="submit">Lọc</button></form>{error!==undefined&&<AlertPanel error={error}/>} {loading?<PageState kind="loading"/>:items.length===0?<PageState kind="empty"/>:<div className="table-wrap"><table className="table"><thead><tr><th>Doanh nghiệp</th><th>Timezone</th><th>Trạng thái</th><th>Revision</th></tr></thead><tbody>{items.map(t=><tr key={id(t.id)}><td><AppLink to={`/platform/tenants/${id(t.id)}`}>{t.profile.displayName}</AppLink></td><td>{t.profile.timeZoneIana}</td><td><StatusBadge>{t.status}</StatusBadge></td><td>{t.revision}</td></tr>)}</tbody></table></div>}</main></Shell> }
function TenantDetail({ tenantId }: { tenantId: string }) { const [tenant,setTenant]=useState<Tenant>();const [reason,setReason]=useState('');const [error,setError]=useState<unknown>();const load=async()=>{try{setTenant(await api.request<Tenant>(`/api/v1/platform/tenants/${tenantId}`));setError(undefined)}catch(e){setError(e)}};useEffect(()=>{void load()},[tenantId]);const change=async(action:'suspend'|'reactivate')=>{if(!tenant)return;try{await api.request(`/api/v1/platform/tenants/${tenantId}/${action}`,{method:'POST',body:{expectedRevision:tenant.revision,operationId:crypto.randomUUID(),reason}});await load()}catch(e){setError(e)}};return <Shell><main className="page">{error!==undefined&&<AlertPanel error={error}/>} {!tenant?<PageState kind="loading"/>:<><h1>{tenant.profile.displayName}</h1><section className="section"><p>Tenant: {id(tenant.id)} · <StatusBadge>{tenant.status}</StatusBadge> · revision {tenant.revision}</p><FormField label="Lý do hỗ trợ"><input value={reason} onChange={e=>setReason(e.target.value)}/></FormField><div className="actions">{tenant.status==='Active'?<button className="co-button co-button-secondary" disabled={!reason} type="button" onClick={()=>void change('suspend')}>Tạm ngưng</button>:<button className="co-button co-button-primary" disabled={!reason} type="button" onClick={()=>void change('reactivate')}>Kích hoạt lại</button>}</div></section></>}</main></Shell> }
const routes: RouteDefinition[] = [{path:'/',render:()=> <Dashboard/>},{path:'/platform',render:()=> <Dashboard/>},{path:'/platform/tenants',render:()=> <Tenants/>},{path:'/platform/tenants/:id',render:m=><TenantDetail tenantId={m.params.id}/> }]
export function App() { return <Router routes={routes} notFound={<PageState kind="not-found"/>}/> }
