using CommerceOS.MockPaymentProvider.Application;
using CommerceOS.MockPaymentProvider.Domain;
namespace CommerceOS.MockPaymentProvider.UnitTests;

public sealed class ProviderTests
{
    [Fact] public async Task TimeoutAfterCommitIsQueryableAndIdempotent() { var store = new Store(); var provider = new DeterministicProvider(store); var first = await provider.CaptureAsync("key", "same", "order", 100, ProviderScenario.TimeoutAfterCommit, default); var replay = await provider.CaptureAsync("key", "same", "order", 100, ProviderScenario.TimeoutAfterCommit, default); Assert.Equal(ProviderOutcome.TimedOut, first.Outcome); Assert.Equal(first.Intent, replay.Intent); Assert.Equal(ProviderPaymentStatus.Captured, first.Intent!.Status); Assert.Equal(first.Intent, await provider.QueryAsync(first.Intent.Id, default)); }
    [Fact] public async Task ScenarioAndIncompatibleReuseAreDeterministic() { var provider = new DeterministicProvider(new Store()); var delayed = await provider.CaptureAsync("delayed", "same", "order", 100, ProviderScenario.DelayedSuccess, default); var duplicate = await provider.CaptureAsync("duplicate", "same", "order", 100, ProviderScenario.DuplicateWebhook, default); var conflict = await provider.CaptureAsync("duplicate", "changed", "order", 100, ProviderScenario.DuplicateWebhook, default); var transient = await provider.CaptureAsync("error", "same", "order", 100, ProviderScenario.Provider500, default); Assert.Equal(ProviderOutcome.Pending, delayed.Outcome); Assert.Equal(2, duplicate.DuplicateWebhookCount); Assert.Equal(ProviderOutcome.IdempotencyConflict, conflict.Outcome); Assert.Equal(ProviderOutcome.TransientFailure, transient.Outcome); }
    [Fact] public async Task WebhooksAreDeterministicAndSigned() { var provider = new DeterministicProvider(new Store()); var result = await provider.CaptureAsync("before", "same", "order", 100, ProviderScenario.WebhookBeforeResponse, default); var webhooks = DeterministicProvider.BuildWebhooks(result, "test-secret"); Assert.Single(webhooks); Assert.Equal(0, webhooks[0].Sequence); Assert.True(DeterministicProvider.VerifyWebhook(webhooks[0], "test-secret")); Assert.False(DeterministicProvider.VerifyWebhook(webhooks[0], "wrong-secret")); }
    private sealed class Store : IProviderOperationStore { private readonly Dictionary<string, ProviderOperation> _items = []; public Task<ProviderOperation?> GetAsync(string idempotencyKey, CancellationToken ct) => Task.FromResult(_items.GetValueOrDefault(idempotencyKey)); public Task<ProviderPaymentIntent?> GetIntentAsync(string intentId, CancellationToken ct) => Task.FromResult(_items.Values.Select(x => x.Intent).SingleOrDefault(x => x.Id == intentId)); public Task<bool> PutAsync(ProviderOperation operation, CancellationToken ct) => Task.FromResult(_items.TryAdd(operation.IdempotencyKey, operation)); }
}
