<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Modules/SubscriptionBilling/CommerceOS.SubscriptionBilling.Application/CommerceOS.SubscriptionBilling.Application.csproj" />
    <ProjectReference Include="../../src/Modules/SubscriptionBilling/CommerceOS.SubscriptionBilling.Infrastructure/CommerceOS.SubscriptionBilling.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../src/Modules/SubscriptionBilling/catalog/initial-catalog.v1.json" Link="initial-catalog.v1.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
