<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CommerceOS.Payments.Domain/CommerceOS.Payments.Domain.csproj" /><ProjectReference Include="../CommerceOS.Payments.Contracts/CommerceOS.Payments.Contracts.csproj" /><ProjectReference Include="../../MockPaymentProvider/CommerceOS.MockPaymentProvider.Contracts/CommerceOS.MockPaymentProvider.Contracts.csproj" /></ItemGroup></Project>
