using System.Globalization;
using System.Text;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using CommerceOS.Tenancy.Application.MembershipAdministration;
using CommerceOS.Tenancy.Domain;

namespace CommerceOS.Tenancy.Infrastructure.Persistence;

/// <summary>Tenancy-local transactional implementation of member/invitation guards. Credential digests only are persisted.</summary>
public sealed class DynamoDbMembershipAdministrationStore(IAmazonDynamoDB client, DynamoDbTenancyOptions options) : IMembershipAdministrationStore
{
    public async Task<Membership?> GetMembershipAsync(TenantId tenantId, MembershipId id, CancellationToken ct) => await GetMember(tenantId, id, ct);
    public async Task<Membership?> GetMembershipForSubjectAsync(TenantId tenantId, SubjectId subjectId, CancellationToken ct)
    {
        var x = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(tenantId, $"AUTHORITY#SUBJECT#{E(subjectId.Value)}") }, ct);
        return x.Item.Count == 0 ? null : await GetMember(tenantId, new(x.Item["MembershipId"].S), ct);
    }
    public async Task<MerchantInvitation?> GetInvitationAsync(TenantId tenantId, string id, CancellationToken ct)
    { var x = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(tenantId, $"INVITATION#{E(id)}") }, ct); return x.Item.Count == 0 ? null : ReadInvitation(x.Item); }
    public async Task<MerchantInvitation?> GetPendingInvitationForEmailAsync(TenantId tenantId, string email, CancellationToken ct)
    { var x = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(tenantId, $"INVITATIONEMAIL#{E(email)}") }, ct); return x.Item.Count == 0 ? null : await GetInvitationAsync(tenantId, x.Item["InvitationId"].S, ct); }
    public async Task<MembershipAdministrationOutcome> ApplyMembershipChangeAsync(Membership previous, Membership updated, int max, CancellationToken ct)
    {
        var countDelta = (previous.Status, updated.Status) switch { (MembershipStatus.Disabled, MembershipStatus.Active) => 1, (MembershipStatus.Active, MembershipStatus.Disabled) => -1, _ => 0 };
        var ownerDelta = (previous.Status is MembershipStatus.Active && previous.Role is MerchantRole.Owner ? -1 : 0) + (updated.Status is MembershipStatus.Active && updated.Role is MerchantRole.Owner ? 1 : 0);
        var guardValues = new Dictionary<string, AttributeValue> { [":count"] = N(countDelta), [":owners"] = N(ownerDelta), [":zero"] = N(0), [":one"] = N(1), [":limit"] = N(max) };
        var guardCondition = countDelta > 0 ? "ActiveCount < :limit" : ownerDelta < 0 ? "ActiveOwnerCount > :one" : "attribute_exists(PK)";
        try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = Member(updated), ConditionExpression = "Revision = :revision AND #status = :status AND #role = :role", ExpressionAttributeNames = new() { ["#status"] = "Status", ["#role"] = "Role" }, ExpressionAttributeValues = new() { [":revision"] = N(previous.Revision), [":status"] = S(previous.Status.ToString()), [":role"] = S(previous.Role.ToString()) } } }, new() { Put = new() { TableName = options.TableName, Item = Authority(updated), ConditionExpression = "MembershipId = :membership", ExpressionAttributeValues = new() { [":membership"] = S(previous.Id.Value) } } }, new() { Put = new() { TableName = options.TableName, Item = Discovery(updated) } }, new() { Update = new() { TableName = options.TableName, Key = Key(previous.TenantId, "ACTIVE-MEMBERSHIP-GUARD"), UpdateExpression = "ADD ActiveCount :count, ActiveOwnerCount :owners", ConditionExpression = guardCondition, ExpressionAttributeValues = guardValues } }] }, ct); return MembershipAdministrationOutcome.Applied; }
        catch (TransactionCanceledException) { return countDelta > 0 ? MembershipAdministrationOutcome.LimitReached : ownerDelta < 0 ? MembershipAdministrationOutcome.LastOwnerProtected : MembershipAdministrationOutcome.RevisionConflict; }
    }
    public async Task<InvitationIssueResult> IssueOrResendInvitationAsync(MerchantInvitation invitation, CancellationToken ct)
    {
        var emailKey = Key(invitation.TenantId, $"INVITATIONEMAIL#{E(invitation.NormalizedRecipientEmail)}");
        try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = Invitation(invitation), ConditionExpression = invitation.Revision == 1 ? "attribute_not_exists(PK)" : "Revision = :previous", ExpressionAttributeValues = invitation.Revision == 1 ? null : new() { [":previous"] = N(invitation.Revision - 1) } } }, new() { Put = new() { TableName = options.TableName, Item = new() { ["PK"] = S(P(invitation.TenantId)), ["SK"] = S($"INVITATIONEMAIL#{E(invitation.NormalizedRecipientEmail)}"), ["InvitationId"] = S(invitation.Id), ["Revision"] = N(invitation.Revision) }, ConditionExpression = invitation.Revision == 1 ? "attribute_not_exists(PK)" : "Revision = :previous", ExpressionAttributeValues = invitation.Revision == 1 ? null : new() { [":previous"] = N(invitation.Revision - 1) } } }] }, ct); return new(MembershipAdministrationOutcome.Applied, invitation); }
        catch (TransactionCanceledException) { return new(MembershipAdministrationOutcome.InvitationConflict, null); }
    }
    public async Task<MembershipAdministrationOutcome> RevokeInvitationAsync(MerchantInvitation invitation, CancellationToken ct)
    { try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = Invitation(invitation), ConditionExpression = "Revision = :previous AND #status = :pending", ExpressionAttributeNames = new() { ["#status"] = "Status" }, ExpressionAttributeValues = new() { [":previous"] = N(invitation.Revision - 1), [":pending"] = S(InvitationStatus.Pending.ToString()) } } }, new() { Delete = new() { TableName = options.TableName, Key = Key(invitation.TenantId, $"INVITATIONEMAIL#{E(invitation.NormalizedRecipientEmail)}"), ConditionExpression = "InvitationId = :id", ExpressionAttributeValues = new() { [":id"] = S(invitation.Id) } } }] }, ct); return MembershipAdministrationOutcome.Applied; } catch (TransactionCanceledException) { return MembershipAdministrationOutcome.RevisionConflict; } }
    public async Task<MembershipAdministrationOutcome> AcceptInvitationAsync(MerchantInvitation invitation, Membership membership, int max, CancellationToken ct)
    {
        try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = Invitation(invitation), ConditionExpression = "Revision = :previous AND #status = :pending", ExpressionAttributeNames = new() { ["#status"] = "Status" }, ExpressionAttributeValues = new() { [":previous"] = N(invitation.Revision - 1), [":pending"] = S(InvitationStatus.Pending.ToString()) } } }, new() { Delete = new() { TableName = options.TableName, Key = Key(invitation.TenantId, $"INVITATIONEMAIL#{E(invitation.NormalizedRecipientEmail)}"), ConditionExpression = "InvitationId = :id", ExpressionAttributeValues = new() { [":id"] = S(invitation.Id) } } }, new() { Put = new() { TableName = options.TableName, Item = Member(membership), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Put = new() { TableName = options.TableName, Item = Authority(membership), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Put = new() { TableName = options.TableName, Item = Discovery(membership), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Update = new() { TableName = options.TableName, Key = Key(invitation.TenantId, "ACTIVE-MEMBERSHIP-GUARD"), UpdateExpression = "ADD ActiveCount :one", ConditionExpression = "ActiveCount < :limit", ExpressionAttributeValues = new() { [":one"] = N(1), [":limit"] = N(max) } } }] }, ct); return MembershipAdministrationOutcome.Applied; }
        catch (TransactionCanceledException) { return MembershipAdministrationOutcome.LimitReached; }
    }
    private async Task<Membership?> GetMember(TenantId tenant, MembershipId id, CancellationToken ct) { var x = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(tenant, $"MEMBERSHIP#{E(id.Value)}") }, ct); return x.Item.Count == 0 ? null : ReadMember(x.Item); }
    private static Membership ReadMember(Dictionary<string, AttributeValue> x) => new(new(x["MembershipId"].S), new(x["TenantId"].S), new(x["SubjectId"].S), Enum.Parse<MerchantRole>(x["Role"].S), Enum.Parse<MembershipStatus>(x["Status"].S), long.Parse(x["Revision"].N, CultureInfo.InvariantCulture));
    private static MerchantInvitation ReadInvitation(Dictionary<string, AttributeValue> x) => new(x["InvitationId"].S, new(x["TenantId"].S), x["Email"].S, Enum.Parse<MerchantRole>(x["Role"].S), Enum.Parse<InvitationStatus>(x["Status"].S), x["CredentialDigest"].S, DateTimeOffset.Parse(x["ExpiresAt"].S, CultureInfo.InvariantCulture), long.Parse(x["Revision"].N, CultureInfo.InvariantCulture));
    private static Dictionary<string, AttributeValue> Member(Membership x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"MEMBERSHIP#{E(x.Id.Value)}"), ["MembershipId"] = S(x.Id.Value), ["TenantId"] = S(x.TenantId.Value), ["SubjectId"] = S(x.SubjectId.Value), ["Role"] = S(x.Role.ToString()), ["Status"] = S(x.Status.ToString()), ["Revision"] = N(x.Revision) };
    private static Dictionary<string, AttributeValue> Authority(Membership x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"AUTHORITY#SUBJECT#{E(x.SubjectId.Value)}"), ["MembershipId"] = S(x.Id.Value), ["SubjectId"] = S(x.SubjectId.Value) };
    private static Dictionary<string, AttributeValue> Discovery(Membership x) => new() { ["PK"] = S($"SUBJECT#{E(x.SubjectId.Value)}"), ["SK"] = S($"MEMBERSHIP#{E(x.Id.Value)}#TENANT#{E(x.TenantId.Value)}"), ["MembershipId"] = S(x.Id.Value), ["TenantId"] = S(x.TenantId.Value) };
    private static Dictionary<string, AttributeValue> Invitation(MerchantInvitation x) => new() { ["PK"] = S(P(x.TenantId)), ["SK"] = S($"INVITATION#{E(x.Id)}"), ["InvitationId"] = S(x.Id), ["TenantId"] = S(x.TenantId.Value), ["Email"] = S(x.NormalizedRecipientEmail), ["Role"] = S(x.Role.ToString()), ["Status"] = S(x.Status.ToString()), ["CredentialDigest"] = S(x.CredentialDigest), ["ExpiresAt"] = S(x.ExpiresAt.ToString("O", CultureInfo.InvariantCulture)), ["Revision"] = N(x.Revision) };
    private static Dictionary<string, AttributeValue> Key(TenantId t, string sk) => new() { ["PK"] = S(P(t)), ["SK"] = S(sk) }; private static string P(TenantId t) => $"TENANT#{E(t.Value)}"; private static string E(string s) => Convert.ToBase64String(Encoding.UTF8.GetBytes(s)).TrimEnd('=').Replace('+', '-').Replace('/', '_'); private static AttributeValue S(string x) => new() { S = x }; private static AttributeValue N(long x) => new() { N = x.ToString(CultureInfo.InvariantCulture) };
}
