<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CommerceOS.Storefront.Domain/CommerceOS.Storefront.Domain.csproj" /><ProjectReference Include="../../Catalog/CommerceOS.Catalog.Contracts/CommerceOS.Catalog.Contracts.csproj" /><ProjectReference Include="../../Inventory/CommerceOS.Inventory.Contracts/CommerceOS.Inventory.Contracts.csproj" /><ProjectReference Include="../../Tenancy/CommerceOS.Tenancy.Contracts/CommerceOS.Tenancy.Contracts.csproj" /><ProjectReference Include="../../Sales/CommerceOS.Sales.Contracts/CommerceOS.Sales.Contracts.csproj" /><ProjectReference Include="../../Pricing/CommerceOS.Pricing.Contracts/CommerceOS.Pricing.Contracts.csproj" /></ItemGroup></Project>
