using CommerceOS.Inventory.Application;
using CommerceOS.Inventory.Domain;
using CommerceOS.Tenancy.Application.Authority;
using CommerceOS.Tenancy.Domain;

namespace CommerceOS.Api;

public sealed record WarehouseInput(string Name);
public sealed record InventoryRevisionInput(long ExpectedRevision);
public sealed record StockAdjustmentInput(string ProductId, string WarehouseId, long Quantity, bool Increase);
public sealed record WarehouseResponse(string Id, string Name, string Status, long Revision);
public sealed record StockResponse(string ProductId, string WarehouseId, long OnHand, long Reserved, long Available, long Revision);
public sealed record StockMovementResponse(string Id, string ProductId, string WarehouseId, string Type, long Quantity, string SourceIdentity, string CorrelationId, DateTimeOffset OccurredAt);

public static class MerchantInventoryEndpoints
{
    public static void MapMerchantInventoryEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/inventory/warehouses", async (HttpContext http, IMerchantRequestAuthorityResolver authority, WarehouseService? warehouses, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (warehouses is null) return Unavailable(http); return Results.Ok((await warehouses.ListAsync(scope.Context!, ct)).Select(Map)); });
        app.MapPost("/api/v1/inventory/warehouses", async (WarehouseInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, WarehouseService? warehouses, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (warehouses is null || string.IsNullOrWhiteSpace(input.Name)) return Problem(422, "WAREHOUSE_INVALID", http.TraceIdentifier); try { var warehouse = Warehouse.Create(new WarehouseId(Guid.NewGuid().ToString("N")), scope.Context!.TenantId, input.Name); return Outcome(await warehouses.CreateAsync(scope.Context, warehouse, ct), http.TraceIdentifier, Results.Created($"/api/v1/inventory/warehouses/{warehouse.Id.Value}", Map(warehouse))); } catch (ArgumentException) { return Problem(422, "WAREHOUSE_INVALID", http.TraceIdentifier); } });
        MapWarehouseAction(app, "disable", (service, context, id, revision, ct) => service.DisableAsync(context, id, revision, ct)); MapWarehouseAction(app, "reactivate", (service, context, id, revision, ct) => service.ReactivateAsync(context, id, revision, ct));
        app.MapGet("/api/v1/inventory/stock", async (string? warehouseId, string? productId, string? cursor, int? pageSize, HttpContext http, IMerchantRequestAuthorityResolver authority, IInventoryStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (store is null) return Unavailable(http); var page = await store.ListStockAsync(scope.Context!, warehouseId, productId, cursor, pageSize ?? 20, ct); return Results.Ok(new { items = page.Items.Select(Map), nextCursor = page.NextCursor }); });
        app.MapGet("/api/v1/inventory/movements", async (string? warehouseId, string? productId, HttpContext http, IMerchantRequestAuthorityResolver authority, IInventoryStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (store is null) return Unavailable(http); return Results.Ok((await store.ListMovementsAsync(scope.Context!, warehouseId, productId, ct)).Select(Map)); });
        app.MapPost("/api/v1/inventory/adjustments", async (StockAdjustmentInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, StockOperationService? stock, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (stock is null || input.Quantity <= 0) return Problem(422, "STOCK_ADJUSTMENT_INVALID", http.TraceIdentifier); var source = http.Request.Headers["Idempotency-Key"].ToString(); if (string.IsNullOrWhiteSpace(source)) return Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier); var outcome = input.Increase ? await stock.AdjustIncreaseAsync(scope.Context!, new(input.ProductId), new(input.WarehouseId), input.Quantity, source, ct) : await stock.AdjustDecreaseAsync(scope.Context!, new(input.ProductId), new(input.WarehouseId), input.Quantity, source, ct); return StockOutcome(outcome, http.TraceIdentifier); });
    }
    private static void MapWarehouseAction(WebApplication app, string action, Func<WarehouseService, TrustedInventoryMutationContext, WarehouseId, long, CancellationToken, Task<InventoryOutcome>> execute) => app.MapPost($"/api/v1/inventory/warehouses/{{id}}/{action}", async (string id, InventoryRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, WarehouseService? warehouses, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (warehouses is null) return Unavailable(http); return Outcome(await execute(warehouses, scope.Context!, new(id), input.ExpectedRevision, ct), http.TraceIdentifier); });
    private static async Task<InventoryScope> ReadScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveReadAsync(http, ct); if (!result.IsAuthenticated) return new(null, Results.Unauthorized()); if (result.ReadResolution?.Context is null) return new(null, Failure(result.ReadResolution?.Failure, result.CorrelationId)); return new(new(new InventoryTenantId(result.ReadResolution.Context.TenantId.Value), result.CorrelationId), null); }
    private static async Task<InventoryScope> MutationScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveMutationAsync(http, ct); if (result?.Context is null) return new(null, result is null ? Results.Unauthorized() : Failure(result.Failure, http.TraceIdentifier)); if (result.Context.Role is MerchantRole.Viewer) return new(null, Problem(403, "INVENTORY_MUTATION_FORBIDDEN", http.TraceIdentifier)); return new(new(new InventoryTenantId(result.Context.TenantId.Value), result.Context.CorrelationId), null); }
    private static WarehouseResponse Map(Warehouse warehouse) => new(warehouse.Id.Value, warehouse.Name, warehouse.Status.ToString(), warehouse.Revision); private static StockResponse Map(StockItem item) => new(item.ProductId.Value, item.WarehouseId.Value, item.OnHand, item.Reserved, item.Available, item.Revision); private static StockMovementResponse Map(StockMovement movement) => new(movement.Id, movement.ProductId.Value, movement.WarehouseId.Value, movement.Type.ToString(), movement.Quantity, movement.SourceIdentity, movement.CorrelationId, movement.OccurredAt);
    private static IResult Outcome(InventoryOutcome outcome, string correlationId, IResult? success = null) => outcome switch { InventoryOutcome.Applied or InventoryOutcome.AlreadyApplied => success ?? Results.NoContent(), InventoryOutcome.NotFound => Results.NotFound(), InventoryOutcome.LimitReached => Problem(422, "WAREHOUSE_LIMIT_REACHED", correlationId), InventoryOutcome.RevisionConflict => Problem(409, "INVENTORY_REVISION_CONFLICT", correlationId), _ => Problem(422, "INVENTORY_INVALID", correlationId) }; private static IResult StockOutcome(StockOperationOutcome outcome, string correlationId) => outcome switch { StockOperationOutcome.Applied or StockOperationOutcome.AlreadyApplied => Results.NoContent(), StockOperationOutcome.InsufficientAvailable => Problem(409, "INSUFFICIENT_AVAILABLE_STOCK", correlationId), StockOperationOutcome.RevisionConflict => Problem(409, "INVENTORY_REVISION_CONFLICT", correlationId), _ => Problem(422, "STOCK_ADJUSTMENT_INVALID", correlationId) };
    private static IResult Failure(TenantAuthorityFailure? failure, string correlationId) => failure?.Code switch { TenantAuthorityFailureCode.TenantSelectionRequired => Problem(409, "TENANT_SELECTION_REQUIRED", correlationId), TenantAuthorityFailureCode.AuthorityUnavailable => Unavailable(correlationId), _ => Problem(403, failure?.Code.ToString() ?? "MEMBERSHIP_REQUIRED", correlationId) }; private static IResult Unavailable(HttpContext http) => Unavailable(http.TraceIdentifier); private static IResult Unavailable(string correlationId) => Problem(503, "INVENTORY_UNAVAILABLE", correlationId); private static IResult Problem(int status, string code, string correlationId) => Results.Problem(statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code, ["correlationId"] = correlationId }); private sealed record InventoryScope(TrustedInventoryMutationContext? Context, IResult? Failure);
}
