using CommerceOS.Sales.Application;
using CommerceOS.Sales.Contracts;
using CommerceOS.Sales.Domain;
using CommerceOS.Tenancy.Application.Authority;
using CommerceOS.Tenancy.Domain;

namespace CommerceOS.Api;

public sealed record MerchantOrderResponse(string Id, IReadOnlyList<SalesOrderLine> Lines, long TotalVnd, GuestSnapshot Guest, string Status, long Revision, DateTimeOffset? PlacedAt, string ProcessId, string WorkflowExecutionIdentity, bool WorkflowStartPending);
public sealed record MerchantOrderPageResponse(IReadOnlyList<MerchantOrderResponse> Items, string? NextCursor);
public sealed record MerchantRefundResponse(string Id, string OrderId, string PaymentId, long AmountVnd, string Currency, IReadOnlyList<RefundLine> Lines, string Status, string RequestedBy, DateTimeOffset RequestedAt, string? DecidedBy, DateTimeOffset? DecidedAt, long Revision);
public sealed record MerchantRevisionInput(long ExpectedRevision);
public sealed record MerchantRefundRequestInput(string PaymentId, long AmountVnd, IReadOnlyList<RefundRequestLine> Lines);

public static class MerchantSalesEndpoints
{
    public static void MapMerchantSalesEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/sales/orders", async (string? cursor, int? pageSize, HttpContext http, IMerchantRequestAuthorityResolver authority, SalesOrderService? orders, CancellationToken ct) =>
        { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null) return Unavailable(http); var page = await orders.ListAsync(scope.Context!, cursor, pageSize ?? 20, ct); return Results.Ok(new MerchantOrderPageResponse(page.Items.Select(Map).ToArray(), page.NextCursor)); });
        app.MapGet("/api/v1/sales/orders/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, ISalesOrderStore? store, CancellationToken ct) =>
        { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (store is null) return Unavailable(http); var order = await store.GetAsync(scope.Context!, new SalesOrderId(id), ct); return order is null ? Results.NotFound() : Results.Ok(Map(order)); });
        app.MapPost("/api/v1/sales/orders/{id}/cancel", async (string id, MerchantRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SalesOrderService? orders, CancellationToken ct) =>
        { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null) return Unavailable(http); var source = SourceIdentity(http); return string.IsNullOrWhiteSpace(source) ? Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier) : Progress(await orders.CancelAsync(new(scope.Context!.TenantId.Value, id, source, input.ExpectedRevision, scope.Context.CorrelationId), ct), http.TraceIdentifier); });
        app.MapGet("/api/v1/sales/refunds", async (HttpContext http, IMerchantRequestAuthorityResolver authority, IRefundStore? refunds, CancellationToken ct) =>
        { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (refunds is null) return Unavailable(http); return Results.Ok((await refunds.ListRefundsAsync(scope.Context!, ct)).Select(Map)); });
        app.MapGet("/api/v1/sales/refunds/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, IRefundStore? refunds, CancellationToken ct) =>
        { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (refunds is null) return Unavailable(http); var refund = await refunds.GetRefundAsync(scope.Context!, id, ct); return refund is null ? Results.NotFound() : Results.Ok(Map(refund)); });
        app.MapPost("/api/v1/sales/orders/{id}/refunds", async (string id, MerchantRefundRequestInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, RefundReviewService? refunds, CancellationToken ct) =>
        { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (refunds is null) return Unavailable(http); var source = SourceIdentity(http); return string.IsNullOrWhiteSpace(source) ? Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier) : Refund(await refunds.RequestAsync(new(scope.Context!.TenantId.Value, id, input.PaymentId, input.AmountVnd, "VND", input.Lines, source, scope.ActorId, Role(scope.Role), scope.Context.CorrelationId), ct), http.TraceIdentifier); });
        MapDecision(app, "approve", true); MapDecision(app, "reject", false);
    }
    private static void MapDecision(WebApplication app, string action, bool approve) => app.MapPost($"/api/v1/sales/refunds/{{id}}/{action}", async (string id, MerchantRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, RefundReviewService? refunds, CancellationToken ct) =>
    { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (scope.Role is not MerchantRole.Owner and not MerchantRole.Admin) return Problem(403, "REFUND_DECISION_FORBIDDEN", http.TraceIdentifier); if (refunds is null) return Unavailable(http); var source = SourceIdentity(http); return string.IsNullOrWhiteSpace(source) ? Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier) : Refund(await refunds.DecideAsync(new(scope.Context!.TenantId.Value, id, input.ExpectedRevision, source, scope.ActorId, Role(scope.Role), approve, scope.Context.CorrelationId), ct), http.TraceIdentifier); });
    private static async Task<SalesScope> ReadScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveReadAsync(http, ct); if (!result.IsAuthenticated) return new(null, "", MerchantRole.Viewer, Results.Unauthorized()); if (result.ReadResolution?.Context is null) return new(null, "", MerchantRole.Viewer, Failure(result.ReadResolution?.Failure, result.CorrelationId)); var context = result.ReadResolution.Context; return new(new(new SalesTenantId(context.TenantId.Value), context.CorrelationId), context.SubjectId.Value, context.Role, null); }
    private static async Task<SalesScope> MutationScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveMutationAsync(http, ct); if (result?.Context is null) return new(null, "", MerchantRole.Viewer, result is null ? Results.Unauthorized() : Failure(result.Failure, http.TraceIdentifier)); var context = result.Context; if (context.Role is MerchantRole.Viewer) return new(null, "", context.Role, Problem(403, "SALES_MUTATION_FORBIDDEN", http.TraceIdentifier)); return new(new(new SalesTenantId(context.TenantId.Value), context.CorrelationId), context.SubjectId.Value, context.Role, null); }
    private static MerchantOrderResponse Map(SalesOrder order) => new(order.Id.Value, order.Lines, order.TotalVnd, order.Guest, order.Status.ToString(), order.Revision, order.PlacedAt == DateTimeOffset.MinValue ? null : order.PlacedAt, order.Process.Id, order.Process.WorkflowExecutionIdentity, order.Process.StartPending);
    private static MerchantRefundResponse Map(RefundRequest refund) => new(refund.Id, refund.OrderId.Value, refund.PaymentId, refund.AmountVnd, refund.Currency, refund.Lines, refund.Status.ToString(), refund.RequestedBy, refund.RequestedAt, refund.DecidedBy, refund.DecidedAt, refund.Revision);
    private static string SourceIdentity(HttpContext http) => http.Request.Headers["Idempotency-Key"].ToString();
    private static TrustedRefundRole Role(MerchantRole role) => Enum.Parse<TrustedRefundRole>(role.ToString());
    private static IResult Progress(SalesProgressOutcome result, string correlationId) => result is SalesProgressOutcome.Applied or SalesProgressOutcome.AlreadyApplied ? Results.NoContent() : Problem(result is SalesProgressOutcome.NotFound ? 404 : 409, result is SalesProgressOutcome.NotFound ? "ORDER_NOT_FOUND" : "ORDER_REVISION_CONFLICT", correlationId);
    private static IResult Refund(RefundCommandResult result, string correlationId) => result.Outcome switch { RefundCommandOutcome.Requested or RefundCommandOutcome.Approved or RefundCommandOutcome.Rejected or RefundCommandOutcome.AlreadyApplied => Results.Ok(result), RefundCommandOutcome.NotFound => Results.NotFound(), RefundCommandOutcome.Forbidden => Problem(403, "REFUND_FORBIDDEN", correlationId), RefundCommandOutcome.Conflict => Problem(409, "REFUND_REVISION_CONFLICT", correlationId), _ => Problem(422, "REFUND_INVALID", correlationId) };
    private static IResult Failure(TenantAuthorityFailure? failure, string correlationId) => failure?.Code switch { TenantAuthorityFailureCode.TenantSelectionRequired => Problem(409, "TENANT_SELECTION_REQUIRED", correlationId), TenantAuthorityFailureCode.AuthorityUnavailable => Unavailable(correlationId), _ => Problem(403, failure?.Code.ToString() ?? "MEMBERSHIP_REQUIRED", correlationId) };
    private static IResult Unavailable(HttpContext http) => Unavailable(http.TraceIdentifier); private static IResult Unavailable(string correlationId) => Problem(503, "SALES_UNAVAILABLE", correlationId); private static IResult Problem(int status, string code, string correlationId) => Results.Problem(statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code, ["correlationId"] = correlationId });
    private sealed record SalesScope(TrustedSalesContext? Context, string ActorId, MerchantRole Role, IResult? Failure);
}
