using Amazon.DynamoDBv2;
using Amazon.Runtime;
using CommerceOS.Procurement.Application;
using CommerceOS.Procurement.Domain;
using CommerceOS.Procurement.Infrastructure.Persistence;
using CommerceOS.Tenancy.Application.Authority;
using CommerceOS.Tenancy.Domain;

namespace CommerceOS.Api;

public sealed record ProcurementSupplierInput(string DisplayName);
public sealed record ProcurementLineInput(string ProductId, long Quantity, long UnitPriceVnd);
public sealed record PurchaseOrderInput(string SupplierId, IReadOnlyList<ProcurementLineInput> Lines);
public sealed record ProcurementRevisionInput(long ExpectedRevision);
public sealed record GoodsReceiptInput(IReadOnlyList<GoodsReceiptLine> Lines);
public sealed record GoodsReceiptCorrectionInput(IReadOnlyList<GoodsReceiptLine> Lines);
public sealed record SupplierInvoiceInput(string PurchaseOrderId, string SupplierReference, DateOnly InvoiceDate, long AmountVnd);
public sealed record SupplierPaymentInput(string ExternalReference, DateOnly PaidOn, long AmountVnd);
public sealed record ProcurementSupplierResponse(string Id, string DisplayName, string Status, long Revision);
public sealed record ProcurementPurchaseOrderResponse(string Id, ProcurementSupplierResponse? Supplier, IReadOnlyList<PurchaseOrderLine> Lines, long TotalVnd, string Status, long Revision);
public sealed record ProcurementReceiptResponse(string Id, string PurchaseOrderId, IReadOnlyList<GoodsReceiptLine> Lines, string Status, long Revision);
public sealed record ProcurementInvoiceResponse(string Id, string PurchaseOrderId, string SupplierReference, DateOnly InvoiceDate, long AmountVnd, long ExpectedAmountVnd, string Status, long Revision);
public sealed record ProcurementPaymentResponse(string Id, string SupplierInvoiceId, string ExternalReference, DateOnly PaidOn, long AmountVnd, long Revision);

public static class MerchantProcurementEndpoints
{
    public static void AddMerchantProcurementServices(this IServiceCollection services, IConfiguration configuration)
    {
        var endpoint = configuration["COMMERCEOS_LOCALSTACK_ENDPOINT"]; var table = configuration["COMMERCEOS_PROCUREMENT_TABLE"];
        if (string.IsNullOrWhiteSpace(endpoint) || string.IsNullOrWhiteSpace(table)) return;
        services.AddSingleton<IAmazonDynamoDB>(_ => new AmazonDynamoDBClient(new BasicAWSCredentials("test", "test"), new AmazonDynamoDBConfig { ServiceURL = endpoint, AuthenticationRegion = "us-east-1" }));
        services.AddSingleton(new DynamoDbProcurementOptions(table));
        services.AddSingleton<DynamoDbProcurementStore>();
        services.AddSingleton<IProcurementStore>(provider => provider.GetRequiredService<DynamoDbProcurementStore>());
        services.AddSingleton<IGoodsReceiptStore>(provider => provider.GetRequiredService<DynamoDbProcurementStore>());
        services.AddSingleton<ISupplierInvoiceStore>(provider => provider.GetRequiredService<DynamoDbProcurementStore>());
        services.AddSingleton<SupplierService>(); services.AddSingleton<PurchaseOrderService>(); services.AddSingleton<GoodsReceiptService>(); services.AddSingleton<SupplierInvoiceService>();
    }

    public static void MapMerchantProcurementEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/procurement/suppliers", async (HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierService? suppliers, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return suppliers is null ? Unavailable(http) : Results.Ok((await suppliers.ListAsync(scope.Context!, ct)).Select(Map)); });
        app.MapGet("/api/v1/procurement/suppliers/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, IProcurementStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (store is null) return Unavailable(http); var item = await store.GetSupplierAsync(scope.Context!, new(id), ct); return item is null ? Results.NotFound() : Results.Ok(Map(item)); });
        app.MapPost("/api/v1/procurement/suppliers", async (ProcurementSupplierInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierService? suppliers, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (suppliers is null || string.IsNullOrWhiteSpace(input.DisplayName)) return Problem(422, "SUPPLIER_INVALID", http.TraceIdentifier); var value = new Supplier(new(Guid.NewGuid().ToString("N")), scope.Context!.TenantId, input.DisplayName.Trim(), SupplierStatus.Active, 1); return Procurement(await suppliers.CreateAsync(scope.Context, value, ct), http.TraceIdentifier, Results.Created($"/api/v1/procurement/suppliers/{value.Id.Value}", Map(value))); });
        app.MapPost("/api/v1/procurement/suppliers/{id}/archive", async (string id, ProcurementRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierService? suppliers, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return suppliers is null ? Unavailable(http) : Procurement(await suppliers.ArchiveAsync(scope.Context!, new(id), input.ExpectedRevision, ct), http.TraceIdentifier); });

        app.MapGet("/api/v1/procurement/purchase-orders", async (HttpContext http, IMerchantRequestAuthorityResolver authority, PurchaseOrderService? orders, IProcurementStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null || store is null) return Unavailable(http); return Results.Ok(await MapOrders(await orders.ListAsync(scope.Context!, ct), store, scope.Context!, ct)); });
        app.MapGet("/api/v1/procurement/purchase-orders/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, PurchaseOrderService? orders, IProcurementStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null || store is null) return Unavailable(http); var item = await orders.GetAsync(scope.Context!, new(id), ct); return item is null ? Results.NotFound() : Results.Ok(await MapOrder(item, store, scope.Context!, ct)); });
        app.MapPost("/api/v1/procurement/purchase-orders", async (PurchaseOrderInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, PurchaseOrderService? orders, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null) return Unavailable(http); try { var value = PurchaseOrder.Draft(new(Guid.NewGuid().ToString("N")), scope.Context!.TenantId, new(input.SupplierId), input.Lines.Select(x => PurchaseOrderLine.Create(x.ProductId, "pending", null, x.Quantity, x.UnitPriceVnd)).ToArray()); return Procurement(await orders.CreateDraftAsync(scope.Context, value, ct), http.TraceIdentifier, Results.Created($"/api/v1/procurement/purchase-orders/{value.Id.Value}", new { id = value.Id.Value })); } catch (ArgumentException) { return Problem(422, "PURCHASE_ORDER_INVALID", http.TraceIdentifier); } });
        app.MapPut("/api/v1/procurement/purchase-orders/{id}", async (string id, PurchaseOrderInput input, ProcurementRevisionInput revision, HttpContext http, IMerchantRequestAuthorityResolver authority, PurchaseOrderService? orders, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (orders is null) return Unavailable(http); try { return Procurement(await orders.UpdateDraftAsync(scope.Context!, new(id), new(input.SupplierId), input.Lines.Select(x => PurchaseOrderLine.Create(x.ProductId, "pending", null, x.Quantity, x.UnitPriceVnd)).ToArray(), revision.ExpectedRevision, ct), http.TraceIdentifier); } catch (ArgumentOutOfRangeException) { return Problem(422, "PURCHASE_ORDER_INVALID", http.TraceIdentifier); } });
        MapOrderAction(app, "submit", (service, context, id, revision, ct) => service.SubmitAsync(context, id, revision, ct)); MapOrderAction(app, "cancel", (service, context, id, revision, ct) => service.CancelAsync(context, id, revision, ct));

        app.MapGet("/api/v1/procurement/purchase-orders/{id}/receipts", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, GoodsReceiptService? receipts, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return receipts is null ? Unavailable(http) : Results.Ok((await receipts.ListAsync(scope.Context!, new(id), ct)).Select(Map)); });
        app.MapPost("/api/v1/procurement/purchase-orders/{id}/receipts", async (string id, GoodsReceiptInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, GoodsReceiptService? receipts, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (receipts is null) return Unavailable(http); var value = new GoodsReceipt(Guid.NewGuid().ToString("N"), new(id), scope.Context!.TenantId, input.Lines, GoodsReceiptStatus.Draft, null, 1); return Procurement(await receipts.CreateDraftAsync(scope.Context, value, ct), http.TraceIdentifier, Results.Created($"/api/v1/procurement/goods-receipts/{value.Id}", Map(value))); });
        app.MapGet("/api/v1/procurement/goods-receipts/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, GoodsReceiptService? receipts, IGoodsReceiptStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (receipts is null || store is null) return Unavailable(http); var item = await receipts.GetAsync(scope.Context!, id, ct); return item is null ? Results.NotFound() : Results.Ok(new { receipt = Map(item), corrections = (await store.ListCorrectionsAsync(scope.Context!, id, ct)).Select(x => new { x.Id, x.Lines, x.Revision }) }); });
        app.MapPost("/api/v1/procurement/goods-receipts/{id}/confirm", async (string id, ProcurementRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, GoodsReceiptService? receipts, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; var source = Source(http); return receipts is null ? Unavailable(http) : string.IsNullOrWhiteSpace(source) ? Idempotency(http) : Procurement(await receipts.ConfirmAsync(scope.Context!, id, input.ExpectedRevision, source, ct), http.TraceIdentifier); });
        app.MapPost("/api/v1/procurement/goods-receipts/{id}/corrections", async (string id, GoodsReceiptCorrectionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, GoodsReceiptService? receipts, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; var source = Source(http); return receipts is null ? Unavailable(http) : string.IsNullOrWhiteSpace(source) ? Idempotency(http) : Procurement(await receipts.CorrectAsync(scope.Context!, new(Guid.NewGuid().ToString("N"), id, scope.Context!.TenantId, input.Lines, source, 1), ct), http.TraceIdentifier); });

        app.MapGet("/api/v1/procurement/supplier-invoices", async (HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierInvoiceService? invoices, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return invoices is null ? Unavailable(http) : Results.Ok((await invoices.ListAsync(scope.Context!, ct)).Select(Map)); });
        app.MapGet("/api/v1/procurement/supplier-invoices/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, ISupplierInvoiceStore? store, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (store is null) return Unavailable(http); var item = await store.GetInvoiceAsync(scope.Context!, id, ct); return item is null ? Results.NotFound() : Results.Ok(Map(item)); });
        app.MapPost("/api/v1/procurement/supplier-invoices", async (SupplierInvoiceInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierInvoiceService? invoices, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; var source = Source(http); if (invoices is null) return Unavailable(http); if (string.IsNullOrWhiteSpace(source)) return Idempotency(http); var value = new SupplierInvoice(Guid.NewGuid().ToString("N"), new(input.PurchaseOrderId), scope.Context!.TenantId, input.SupplierReference, input.InvoiceDate, input.AmountVnd, SupplierInvoiceStatus.Accepted, 0, source, 1); return Invoice(await invoices.RecordInvoiceAsync(scope.Context, value, ct), http.TraceIdentifier, Results.Created($"/api/v1/procurement/supplier-invoices/{value.Id}", Map(value))); });
        app.MapPost("/api/v1/procurement/supplier-invoices/{id}/approve-variance", async (string id, ProcurementRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierInvoiceService? invoices, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (scope.Role is not MerchantRole.Owner and not MerchantRole.Admin) return Problem(403, "INVOICE_VARIANCE_APPROVAL_FORBIDDEN", http.TraceIdentifier); return invoices is null ? Unavailable(http) : Invoice(await invoices.ApproveVarianceAsync(new(scope.Context!.TenantId, scope.ActorId, true, scope.Context.CorrelationId), id, input.ExpectedRevision, ct), http.TraceIdentifier); });
        app.MapGet("/api/v1/procurement/supplier-invoices/{id}/payments", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierInvoiceService? invoices, CancellationToken ct) => { var scope = await ReadScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return invoices is null ? Unavailable(http) : Results.Ok((await invoices.ListPaymentsAsync(scope.Context!, id, ct)).Select(Map)); });
        app.MapPost("/api/v1/procurement/supplier-invoices/{id}/payments", async (string id, SupplierPaymentInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, SupplierInvoiceService? invoices, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; var source = Source(http); if (invoices is null) return Unavailable(http); if (string.IsNullOrWhiteSpace(source)) return Idempotency(http); var payment = new SupplierPayment(Guid.NewGuid().ToString("N"), id, scope.Context!.TenantId, input.ExternalReference, input.PaidOn, input.AmountVnd, source, 1); return Invoice(await invoices.RecordPaymentAsync(scope.Context, payment, ct), http.TraceIdentifier); });
    }

    private static void MapOrderAction(WebApplication app, string action, Func<PurchaseOrderService, TrustedProcurementMutationContext, PurchaseOrderId, long, CancellationToken, Task<ProcurementOutcome>> command) => app.MapPost($"/api/v1/procurement/purchase-orders/{{id}}/{action}", async (string id, ProcurementRevisionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, PurchaseOrderService? orders, CancellationToken ct) => { var scope = await MutationScope(authority, http, ct); if (scope.Failure is not null) return scope.Failure; return orders is null ? Unavailable(http) : Procurement(await command(orders, scope.Context!, new(id), input.ExpectedRevision, ct), http.TraceIdentifier); });
    private static async Task<IReadOnlyList<ProcurementPurchaseOrderResponse>> MapOrders(IReadOnlyList<PurchaseOrder> values, IProcurementStore store, TrustedProcurementMutationContext context, CancellationToken ct) { var results = new List<ProcurementPurchaseOrderResponse>(values.Count); foreach (var value in values) results.Add(await MapOrder(value, store, context, ct)); return results; }
    private static async Task<ProcurementPurchaseOrderResponse> MapOrder(PurchaseOrder value, IProcurementStore store, TrustedProcurementMutationContext context, CancellationToken ct) { var supplier = await store.GetSupplierAsync(context, value.SupplierId, ct); return new(value.Id.Value, supplier is null ? null : Map(supplier), value.Lines, value.Lines.Sum(x => checked(x.Quantity * x.UnitPriceVnd)), value.Status.ToString(), value.Revision); }
    private static ProcurementSupplierResponse Map(Supplier x) => new(x.Id.Value, x.DisplayName, x.Status.ToString(), x.Revision); private static ProcurementReceiptResponse Map(GoodsReceipt x) => new(x.Id, x.PurchaseOrderId.Value, x.Lines, x.Status.ToString(), x.Revision); private static ProcurementInvoiceResponse Map(SupplierInvoice x) => new(x.Id, x.PurchaseOrderId.Value, x.SupplierReference, x.InvoiceDate, x.AmountVnd, x.ExpectedAmountVnd, x.Status.ToString(), x.Revision); private static ProcurementPaymentResponse Map(SupplierPayment x) => new(x.Id, x.SupplierInvoiceId, x.ExternalReference, x.PaidOn, x.AmountVnd, x.Revision);
    private static async Task<ProcurementScope> ReadScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveReadAsync(http, ct); if (!result.IsAuthenticated) return new(null, "", MerchantRole.Viewer, Results.Unauthorized()); if (result.ReadResolution?.Context is null) return new(null, "", MerchantRole.Viewer, Failure(result.ReadResolution?.Failure, result.CorrelationId)); var context = result.ReadResolution.Context; return new(new(new ProcurementTenantId(context.TenantId.Value), context.CorrelationId), context.SubjectId.Value, context.Role, null); }
    private static async Task<ProcurementScope> MutationScope(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveMutationAsync(http, ct); if (result?.Context is null) return new(null, "", MerchantRole.Viewer, result is null ? Results.Unauthorized() : Failure(result.Failure, http.TraceIdentifier)); var context = result.Context; return context.Role is MerchantRole.Viewer ? new(null, "", context.Role, Problem(403, "PROCUREMENT_MUTATION_FORBIDDEN", http.TraceIdentifier)) : new(new(new ProcurementTenantId(context.TenantId.Value), context.CorrelationId), context.SubjectId.Value, context.Role, null); }
    private static string Source(HttpContext http) => http.Request.Headers["Idempotency-Key"].ToString();
    private static IResult Procurement(ProcurementOutcome result, string correlationId, IResult? success = null) => result switch { ProcurementOutcome.Applied => success ?? Results.NoContent(), ProcurementOutcome.NotFound => Results.NotFound(), ProcurementOutcome.RevisionConflict => Problem(409, "PROCUREMENT_REVISION_CONFLICT", correlationId), ProcurementOutcome.ProductNotPurchasable => Problem(422, "PRODUCT_NOT_PURCHASABLE", correlationId), ProcurementOutcome.SupplierNotActive => Problem(422, "SUPPLIER_NOT_ACTIVE", correlationId), _ => Problem(422, "PROCUREMENT_INVALID", correlationId) };
    private static IResult Invoice(SupplierInvoiceOutcome result, string correlationId, IResult? success = null) => result switch { SupplierInvoiceOutcome.Applied or SupplierInvoiceOutcome.AlreadyApplied => success ?? Results.NoContent(), SupplierInvoiceOutcome.NotFound => Results.NotFound(), SupplierInvoiceOutcome.Forbidden => Problem(403, "INVOICE_FORBIDDEN", correlationId), SupplierInvoiceOutcome.ReceiptIncomplete => Problem(422, "PURCHASE_ORDER_NOT_FULLY_RECEIVED", correlationId), SupplierInvoiceOutcome.InvoiceConflict => Problem(409, "SUPPLIER_INVOICE_CONFLICT", correlationId), SupplierInvoiceOutcome.VarianceApprovalRequired => Problem(422, "INVOICE_VARIANCE_APPROVAL_REQUIRED", correlationId), _ => Problem(422, "SUPPLIER_INVOICE_INVALID", correlationId) };
    private static IResult Idempotency(HttpContext http) => Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier); private static IResult Failure(TenantAuthorityFailure? failure, string correlationId) => failure?.Code switch { TenantAuthorityFailureCode.TenantSelectionRequired => Problem(409, "TENANT_SELECTION_REQUIRED", correlationId), TenantAuthorityFailureCode.AuthorityUnavailable => Unavailable(correlationId), _ => Problem(403, failure?.Code.ToString() ?? "MEMBERSHIP_REQUIRED", correlationId) }; private static IResult Unavailable(HttpContext http) => Unavailable(http.TraceIdentifier); private static IResult Unavailable(string correlationId) => Problem(503, "PROCUREMENT_UNAVAILABLE", correlationId); private static IResult Problem(int status, string code, string correlationId) => Results.Problem(statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code, ["correlationId"] = correlationId }); private sealed record ProcurementScope(TrustedProcurementMutationContext? Context, string ActorId, MerchantRole Role, IResult? Failure);
}
