using Amazon.DynamoDBv2;
using Amazon.Runtime;
using CommerceOS.Tenancy.Application.Authority;
using CommerceOS.Tenancy.Application.MembershipAdministration;
using CommerceOS.Tenancy.Domain;
using CommerceOS.Tenancy.Infrastructure.Persistence;
using CommerceOS.Notification.Application;
using CommerceOS.Notification.Infrastructure.Persistence;
using CommerceOS.Audit.Application;
using CommerceOS.Audit.Infrastructure.Persistence;
using CommerceOS.SubscriptionBilling.Application.Catalog;
using CommerceOS.SubscriptionBilling.Application.PaidLifecycle;
using CommerceOS.SubscriptionBilling.Application.Trial;
using CommerceOS.SubscriptionBilling.Contracts;

namespace CommerceOS.Api;

public sealed record InvitationInput(string RecipientEmail, string Role);
public sealed record MembershipChangeInput(string Role, string Status, long ExpectedRevision);
public sealed record InviteRevisionInput(long ExpectedRevision);
public sealed record SubscriptionPlanInput(string PlanId, string PlanVersionId, long? ExpectedRevision = null);
public static class MerchantSettingsEndpoints
{
    public static void AddMerchantSettingsServices(this IServiceCollection services, IConfiguration configuration)
    { var endpoint = configuration["COMMERCEOS_LOCALSTACK_ENDPOINT"]; var table = configuration["COMMERCEOS_TENANCY_TABLE"]; if (string.IsNullOrWhiteSpace(endpoint) || string.IsNullOrWhiteSpace(table)) return; services.AddSingleton<IAmazonDynamoDB>(_ => new AmazonDynamoDBClient(new BasicAWSCredentials("test", "test"), new AmazonDynamoDBConfig { ServiceURL = endpoint, AuthenticationRegion = "us-east-1" })); services.AddSingleton(new DynamoDbTenancyOptions(table)); services.AddSingleton<IMembershipAdministrationStore, DynamoDbMembershipAdministrationStore>(); services.AddSingleton<MembershipAdministrationService>(); var notificationTable = configuration["COMMERCEOS_NOTIFICATION_TABLE"]; if (!string.IsNullOrWhiteSpace(notificationTable)) { services.AddSingleton(new DynamoDbNotificationOptions(notificationTable)); services.AddSingleton<INotificationStore, DynamoDbNotificationStore>(); services.AddSingleton<NotificationCommandService>(); } var auditTable = configuration["COMMERCEOS_AUDIT_TABLE"]; if (!string.IsNullOrWhiteSpace(auditTable)) { services.AddSingleton(new DynamoDbAuditOptions(auditTable)); services.AddSingleton<IAuditStore, DynamoDbAuditStore>(); services.AddSingleton<AuditService>(); } }
    public static void MapMerchantSettingsEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/settings/team/members", async (HttpContext h, IMerchantRequestAuthorityResolver a, MembershipAdministrationService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Results.Ok(await s.ListMembershipsAsync(x.Read!, ct)); });
        app.MapGet("/api/v1/settings/team/invitations", async (HttpContext h, IMerchantRequestAuthorityResolver a, MembershipAdministrationService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Results.Ok((await s.ListInvitationsAsync(x.Read!, ct)).Select(i => new { i.Id, i.NormalizedRecipientEmail, i.Role, i.Status, i.ExpiresAt, i.Revision })); });
        app.MapPost("/api/v1/settings/team/invitations", async (InvitationInput i, HttpContext h, IMerchantRequestAuthorityResolver a, MembershipAdministrationService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; if (s is null) return Off(h); if (!Enum.TryParse<MerchantRole>(i.Role, true, out var role)) return Bad(422, "INVITATION_INVALID", h.TraceIdentifier); var r = await s.IssueInvitationAsync(x.Mutate!, i.RecipientEmail, role, ct); return r.Outcome is MembershipAdministrationOutcome.Applied ? Results.Created($"/api/v1/settings/team/invitations/{r.Invitation!.Id}", new { r.Invitation.Id, r.Invitation.NormalizedRecipientEmail, r.Invitation.Role, r.Invitation.Status, r.Invitation.ExpiresAt, r.Invitation.Revision, credential = r.Credential }) : Result(r.Outcome, h.TraceIdentifier); });
        app.MapPost("/api/v1/settings/team/invitations/{id}/revoke", async (string id, InviteRevisionInput i, HttpContext h, IMerchantRequestAuthorityResolver a, MembershipAdministrationService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Result(await s.RevokeInvitationAsync(x.Mutate!, id, i.ExpectedRevision, ct), h.TraceIdentifier); });
        app.MapPatch("/api/v1/settings/team/members/{id}", async (string id, MembershipChangeInput i, HttpContext h, IMerchantRequestAuthorityResolver a, MembershipAdministrationService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; if (s is null) return Off(h); if (!Enum.TryParse<MerchantRole>(i.Role, true, out var role) || !Enum.TryParse<MembershipStatus>(i.Status, true, out var status)) return Bad(422, "MEMBERSHIP_INVALID", h.TraceIdentifier); return Result(await s.ChangeMembershipAsync(x.Mutate!, new(id), status, role, i.ExpectedRevision, ct), h.TraceIdentifier); });
        app.MapGet("/api/v1/settings/notifications", async (int? pageSize, HttpContext h, IMerchantRequestAuthorityResolver a, NotificationCommandService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Results.Ok(await s.ListAsync(x.Read!.TenantId.Value, x.Read.SubjectId.Value, pageSize ?? 50, ct)); });
        app.MapPost("/api/v1/settings/notifications/{id}/read", async (string id, HttpContext h, IMerchantRequestAuthorityResolver a, NotificationCommandService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Notification(await s.ReadAsync(x.Read!.TenantId.Value, id, x.Read.SubjectId.Value, ct), h.TraceIdentifier); });
        app.MapPost("/api/v1/settings/notifications/{id}/acknowledge", async (string id, HttpContext h, IMerchantRequestAuthorityResolver a, NotificationCommandService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Notification(await s.AcknowledgeAsync(x.Read!.TenantId.Value, id, x.Read.SubjectId.Value, ct), h.TraceIdentifier); });
        app.MapGet("/api/v1/settings/audit", async (DateTimeOffset? from, int? limit, HttpContext h, IMerchantRequestAuthorityResolver a, AuditService? s, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; if (x.Read!.Role is not MerchantRole.Owner and not MerchantRole.Admin) return Bad(403, "AUDIT_FORBIDDEN", h.TraceIdentifier); return s is null ? Off(h) : Results.Ok(await s.ListTenantAsync(new(x.Read.TenantId.Value, x.Read.Role.ToString(), x.Read.CorrelationId), from ?? DateTimeOffset.UtcNow.AddDays(-30), limit ?? 50, ct)); });
        app.MapGet("/api/v1/settings/subscription/plans", async (ISubscriptionCatalogQuery? s, CancellationToken ct) => s is null ? Results.Problem(statusCode: 503, title: "SUBSCRIPTION_UNAVAILABLE") : Results.Ok(await s.ListAvailablePlanVersionsAsync(ct)));
        app.MapGet("/api/v1/settings/subscription/current", async (HttpContext h, IMerchantRequestAuthorityResolver a, IPaidSubscriptionStore? paid, ITrialSubscriptionStore? trial, CancellationToken ct) => { var x = await Read(a, h, ct); if (x.Error is not null) return x.Error; if (paid is null || trial is null) return Off(h); var tenant = x.Read!.TenantId.Value; var currentPaid = await paid.GetCurrentAsync(tenant, ct); return Results.Ok(new { paid = currentPaid, trial = currentPaid is null ? await trial.GetCurrentForTenantAsync(tenant, ct) : null }); });
        app.MapPost("/api/v1/settings/subscription/activate-or-upgrade", async (SubscriptionPlanInput i, HttpContext h, IMerchantRequestAuthorityResolver a, PaidSubscriptionLifecycleService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; if (s is null) return Off(h); try { return Paid(await s.ActivateOrUpgradeAsync(new(x.Mutate!.TenantId.Value, i.PlanId, i.PlanVersionId, Source(h), x.Mutate.CorrelationId), ct), h.TraceIdentifier); } catch (ArgumentException) { return Bad(422, "SUBSCRIPTION_INVALID", h.TraceIdentifier); } });
        app.MapPost("/api/v1/settings/subscription/downgrade", async (SubscriptionPlanInput i, HttpContext h, IMerchantRequestAuthorityResolver a, PaidSubscriptionLifecycleService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; if (s is null || i.ExpectedRevision is null) return Bad(422, "SUBSCRIPTION_INVALID", h.TraceIdentifier); try { return Paid(await s.RequestDowngradeAsync(new(x.Mutate!.TenantId.Value, i.PlanId, i.PlanVersionId, i.ExpectedRevision.Value, Source(h)), ct), h.TraceIdentifier); } catch (InvalidOperationException) { return Bad(422, "SUBSCRIPTION_DOWNGRADE_INVALID", h.TraceIdentifier); } });
        app.MapPost("/api/v1/settings/subscription/cancel-renewal", async (InviteRevisionInput i, HttpContext h, IMerchantRequestAuthorityResolver a, PaidSubscriptionLifecycleService? s, CancellationToken ct) => { var x = await Mutate(a, h, ct); if (x.Error is not null) return x.Error; return s is null ? Off(h) : Paid(await s.CancelRenewalAsync(x.Mutate!.TenantId.Value, i.ExpectedRevision, ct), h.TraceIdentifier); });
    }
    private static async Task<SettingsScope> Read(IMerchantRequestAuthorityResolver a, HttpContext h, CancellationToken ct) { var r = await a.ResolveReadAsync(h, ct); return !r.IsAuthenticated ? new(null, null, Results.Unauthorized()) : r.ReadResolution?.Context is { } c ? new(c, null, null) : new(null, null, Bad(r.ReadResolution?.Failure is { Code: TenantAuthorityFailureCode.TenantSelectionRequired } ? 409 : 403, r.ReadResolution?.Failure?.Code.ToString() ?? "MEMBERSHIP_REQUIRED", r.CorrelationId)); }
    private static async Task<SettingsScope> Mutate(IMerchantRequestAuthorityResolver a, HttpContext h, CancellationToken ct) { var r = await a.ResolveMutationAsync(h, ct); return r?.Context is { } c && c.Role is MerchantRole.Owner or MerchantRole.Admin ? new(null, c, null) : new(null, null, r is null ? Results.Unauthorized() : Bad(403, "TEAM_MUTATION_FORBIDDEN", h.TraceIdentifier)); }
    private static IResult Result(MembershipAdministrationOutcome x, string c) => x is MembershipAdministrationOutcome.Applied or MembershipAdministrationOutcome.AlreadyApplied ? Results.NoContent() : Bad(x is MembershipAdministrationOutcome.NotFound ? 404 : x is MembershipAdministrationOutcome.RevisionConflict or MembershipAdministrationOutcome.InvitationConflict ? 409 : 422, $"TEAM_{x.ToString().ToUpperInvariant()}", c); private static IResult Notification(NotificationOutcome x, string c) => x is NotificationOutcome.Applied or NotificationOutcome.AlreadyApplied ? Results.NoContent() : x is NotificationOutcome.NotFound ? Results.NotFound() : Bad(422, $"NOTIFICATION_{x.ToString().ToUpperInvariant()}", c); private static IResult Paid(PaidLifecycleResult x, string c) => x.Outcome is PaidLifecycleOutcome.Applied or PaidLifecycleOutcome.AlreadyApplied ? Results.Ok(x) : Bad(x.Outcome is PaidLifecycleOutcome.AwaitingChargeEvidence ? 202 : x.Outcome is PaidLifecycleOutcome.RevisionConflict ? 409 : 422, $"SUBSCRIPTION_{x.Outcome.ToString().ToUpperInvariant()}", c); private static string Source(HttpContext h) => h.Request.Headers["Idempotency-Key"].ToString(); private static IResult Off(HttpContext h) => Bad(503, "SETTINGS_UNAVAILABLE", h.TraceIdentifier); private static IResult Bad(int s, string c, string i) => Results.Problem(statusCode: s, title: c, extensions: new Dictionary<string, object?> { { "code", c }, { "correlationId", i } }); private sealed record SettingsScope(TrustedTenantReadContext? Read, TrustedTenantMutationContext? Mutate, IResult? Error);
}
