using Amazon.DynamoDBv2;
using Amazon.Runtime;
using CommerceOS.Customer.Application;
using CommerceOS.Customer.Contracts;
using CommerceOS.Customer.Infrastructure.Persistence;
using CommerceOS.Pricing.Application;
using CommerceOS.Pricing.Infrastructure.Persistence;
using CommerceOS.Tenancy.Application.Authority;
using CommerceOS.Tenancy.Domain;

namespace CommerceOS.Api;

public sealed record CustomerInput(string DisplayName, string? Email, string? Phone, bool EmailOptIn, bool SmsOptIn, long? ExpectedRevision = null);
public sealed record PromotionInput(string ProductId, long PromotionalUnitPriceVnd, DateTimeOffset EffectiveFrom, DateTimeOffset EffectiveUntil);
public sealed record PromotionResponse(string Id, string ProductId, long PromotionalUnitPriceVnd, DateTimeOffset EffectiveFrom, DateTimeOffset EffectiveUntil, DateTimeOffset AcceptedAt, DateTimeOffset? CancelledAt, string Status, long? CurrentBasePriceVnd, bool CurrentlyBeneficial);

public static class MerchantCustomerPricingEndpoints
{
    public static void AddMerchantCustomerPricingServices(this IServiceCollection services, IConfiguration configuration)
    {
        var endpoint = configuration["COMMERCEOS_LOCALSTACK_ENDPOINT"]; var customer = configuration["COMMERCEOS_CUSTOMER_TABLE"]; var pricing = configuration["COMMERCEOS_PRICING_TABLE"];
        if (string.IsNullOrWhiteSpace(endpoint) || string.IsNullOrWhiteSpace(customer) || string.IsNullOrWhiteSpace(pricing)) return;
        services.AddSingleton<IAmazonDynamoDB>(_ => new AmazonDynamoDBClient(new BasicAWSCredentials("test", "test"), new AmazonDynamoDBConfig { ServiceURL = endpoint, AuthenticationRegion = "us-east-1" }));
        services.AddSingleton(new DynamoDbCustomerOptions(customer)); services.AddSingleton<DynamoDbCustomerProfileStore>(); services.AddSingleton<ICustomerProfileStore>(p => p.GetRequiredService<DynamoDbCustomerProfileStore>()); services.AddSingleton<CustomerProfileService>();
        services.AddSingleton(new DynamoDbPricingOptions(pricing)); services.AddSingleton<DynamoDbPromotionStore>(); services.AddSingleton<IPromotionStore>(p => p.GetRequiredService<DynamoDbPromotionStore>()); services.AddSingleton<PromotionService>(); services.AddSingleton<PromotionMerchantQuery>();
    }
    public static void MapMerchantCustomerPricingEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/customers", async (string? search, int? pageSize, HttpContext http, IMerchantRequestAuthorityResolver authority, CustomerProfileService? customers, CancellationToken ct) => { var scope = await Read(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (customers is null) return Unavailable(http); return Results.Ok(await customers.ListAsync(scope.Context!.TenantId, search, pageSize ?? 50, ct)); });
        app.MapGet("/api/v1/customers/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, CustomerProfileService? customers, CancellationToken ct) => { var scope = await Read(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (customers is null) return Unavailable(http); var customer = await customers.GetAsync(scope.Context!.TenantId, id, ct); return customer is null ? Results.NotFound() : Results.Ok(customer); });
        app.MapPost("/api/v1/customers", async (CustomerInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, CustomerProfileService? customers, CancellationToken ct) => { var scope = await Mutate(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (customers is null) return Unavailable(http); var result = await customers.CreateAsync(new(scope.Context!.TenantId, input.DisplayName, input.Email, input.Phone, new(input.EmailOptIn, input.SmsOptIn), scope.Context.CorrelationId), ct); return Customer(result, http.TraceIdentifier, true); });
        app.MapPatch("/api/v1/customers/{id}", async (string id, CustomerInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, CustomerProfileService? customers, CancellationToken ct) => { var scope = await Mutate(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (customers is null || input.ExpectedRevision is null) return Problem(422, "REVISION_REQUIRED", http.TraceIdentifier); var result = await customers.UpdateAsync(new(scope.Context!.TenantId, id, input.DisplayName, input.Email, input.Phone, new(input.EmailOptIn, input.SmsOptIn), input.ExpectedRevision.Value, scope.Context.CorrelationId), ct); return Customer(result, http.TraceIdentifier, false); });
        app.MapGet("/api/v1/pricing/promotions", async (HttpContext http, IMerchantRequestAuthorityResolver authority, PromotionMerchantQuery? promotions, CancellationToken ct) => { var scope = await Read(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (promotions is null) return Unavailable(http); return Results.Ok((await promotions.ListAsync(scope.Context!.TenantId, ct)).Select(Map)); });
        app.MapGet("/api/v1/pricing/promotions/{id}", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, PromotionMerchantQuery? promotions, CancellationToken ct) => { var scope = await Read(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (promotions is null) return Unavailable(http); var promotion = await promotions.GetAsync(scope.Context!.TenantId, id, ct); return promotion is null ? Results.NotFound() : Results.Ok(Map(promotion)); });
        app.MapPost("/api/v1/pricing/promotions", async (PromotionInput input, HttpContext http, IMerchantRequestAuthorityResolver authority, PromotionService? promotions, CancellationToken ct) => { var scope = await PricingMutate(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (promotions is null) return Unavailable(http); var source = Source(http); return string.IsNullOrWhiteSpace(source) ? Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier) : Promotion(await promotions.ScheduleAsync(new(scope.Context!.TenantId, input.ProductId, input.PromotionalUnitPriceVnd, input.EffectiveFrom, input.EffectiveUntil, source, Role(scope.Role), scope.Context.CorrelationId), ct), http.TraceIdentifier); });
        app.MapPost("/api/v1/pricing/promotions/{id}/cancel", async (string id, HttpContext http, IMerchantRequestAuthorityResolver authority, PromotionService? promotions, CancellationToken ct) => { var scope = await PricingMutate(authority, http, ct); if (scope.Failure is not null) return scope.Failure; if (promotions is null) return Unavailable(http); var source = Source(http); return string.IsNullOrWhiteSpace(source) ? Problem(422, "IDEMPOTENCY_KEY_REQUIRED", http.TraceIdentifier) : Promotion(await promotions.CancelAsync(new(scope.Context!.TenantId, id, source, Role(scope.Role), scope.Context.CorrelationId), ct), http.TraceIdentifier); });
    }
    private static async Task<MerchantScope> Read(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveReadAsync(http, ct); if (!result.IsAuthenticated) return new(null, MerchantRole.Viewer, Results.Unauthorized()); if (result.ReadResolution?.Context is null) return new(null, MerchantRole.Viewer, Failure(result.ReadResolution?.Failure, result.CorrelationId)); var x = result.ReadResolution.Context; return new(new(x.TenantId.Value, x.CorrelationId), x.Role, null); }
    private static async Task<MerchantScope> Mutate(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var result = await authority.ResolveMutationAsync(http, ct); if (result?.Context is null) return new(null, MerchantRole.Viewer, result is null ? Results.Unauthorized() : Failure(result.Failure, http.TraceIdentifier)); return result.Context.Role is MerchantRole.Viewer ? new(null, result.Context.Role, Problem(403, "CUSTOMER_MUTATION_FORBIDDEN", http.TraceIdentifier)) : new(new(result.Context.TenantId.Value, result.Context.CorrelationId), result.Context.Role, null); }
    private static async Task<MerchantScope> PricingMutate(IMerchantRequestAuthorityResolver authority, HttpContext http, CancellationToken ct) { var scope = await Mutate(authority, http, ct); return scope.Failure is not null || scope.Role is MerchantRole.Owner or MerchantRole.Admin ? scope : new(null, scope.Role, Problem(403, "PROMOTION_MUTATION_FORBIDDEN", http.TraceIdentifier)); }
    private static IResult Customer((CustomerCommandOutcome Outcome, CustomerProfileView? Customer) result, string correlationId, bool created) => result.Outcome switch { CustomerCommandOutcome.Applied => created ? Results.Created($"/api/v1/customers/{result.Customer!.CustomerId}", result.Customer) : Results.Ok(result.Customer), CustomerCommandOutcome.NotFound => Results.NotFound(), CustomerCommandOutcome.Conflict => Problem(409, "CUSTOMER_REVISION_CONFLICT", correlationId), _ => Problem(422, "CUSTOMER_INVALID", correlationId) };
    private static PromotionResponse Map(PromotionMerchantView value) => new(value.Promotion.Id.Value, value.Promotion.ProductId, value.Promotion.PromotionalUnitPriceVnd, value.Promotion.EffectiveFrom, value.Promotion.EffectiveUntil, value.Promotion.AcceptedAt, value.CancelledAt, value.TemporalStatus, value.CurrentBasePriceVnd, value.CurrentlyBeneficial); private static IResult Promotion(PromotionCommandResult result, string correlationId) => result.Outcome switch { PromotionCommandOutcome.Scheduled => Results.Created($"/api/v1/pricing/promotions/{result.PromotionId}", result), PromotionCommandOutcome.Cancelled or PromotionCommandOutcome.AlreadyApplied => Results.Ok(result), PromotionCommandOutcome.NotFound => Results.NotFound(), PromotionCommandOutcome.Forbidden => Problem(403, "PROMOTION_MUTATION_FORBIDDEN", correlationId), PromotionCommandOutcome.Conflict => Problem(409, "PROMOTION_CONFLICT", correlationId), PromotionCommandOutcome.IneligibleProduct => Problem(422, "PROMOTION_INELIGIBLE_PRODUCT", correlationId), _ => Problem(422, "PROMOTION_INVALID", correlationId) };
    private static TrustedPricingRole Role(MerchantRole role) => Enum.Parse<TrustedPricingRole>(role.ToString()); private static string Source(HttpContext http) => http.Request.Headers["Idempotency-Key"].ToString(); private static IResult Failure(TenantAuthorityFailure? failure, string correlationId) => failure?.Code switch { TenantAuthorityFailureCode.TenantSelectionRequired => Problem(409, "TENANT_SELECTION_REQUIRED", correlationId), TenantAuthorityFailureCode.AuthorityUnavailable => Unavailable(correlationId), _ => Problem(403, failure?.Code.ToString() ?? "MEMBERSHIP_REQUIRED", correlationId) }; private static IResult Unavailable(HttpContext http) => Unavailable(http.TraceIdentifier); private static IResult Unavailable(string correlationId) => Problem(503, "MERCHANT_DATA_UNAVAILABLE", correlationId); private static IResult Problem(int status, string code, string correlationId) => Results.Problem(statusCode: status, title: code, extensions: new Dictionary<string, object?> { ["code"] = code, ["correlationId"] = correlationId }); private sealed record MerchantContext(string TenantId, string CorrelationId); private sealed record MerchantScope(MerchantContext? Context, MerchantRole Role, IResult? Failure);
}
