<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CommerceOS.ProductDataIngestion.Domain/CommerceOS.ProductDataIngestion.Domain.csproj" /><ProjectReference Include="../../SubscriptionBilling/CommerceOS.SubscriptionBilling.Contracts/CommerceOS.SubscriptionBilling.Contracts.csproj" /></ItemGroup></Project>
