from __future__ import annotations


DASHBOARD_HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CommerceOS Orchestrator</title>
<style>
body{font:14px system-ui;margin:0;background:#f5f7fb;color:#182230}header,main{padding:16px 22px}
header{display:flex;justify-content:space-between;align-items:center;background:#ffffff;border-bottom:1px solid #dce3ed}
.cards,.lanes{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}
.card,.panel{background:#ffffff;border:1px solid #dce3ed;border-radius:10px;padding:12px;margin-bottom:12px;box-shadow:0 2px 10px rgba(37,56,82,.05)}
.big{font-size:24px;font-weight:800}.small{font-size:12px;color:#68778a}
.state-pill{display:inline-block;margin-top:5px;padding:4px 9px;border-radius:999px;font-weight:800;font-size:12px;background:#46515f}
.state-running{background:#dff6e9;color:#12633f}.state-finished{background:#e3f0ff;color:#1d5b91}
.state-blocked,.state-human-required{background:#ffe7e2;color:#a43f32}.state-stopping{background:#fff1cc;color:#8a5a00}.state-idle,.state-stopped{background:#e8edf3;color:#526173}
button{padding:9px 14px;border:0;border-radius:7px;font-weight:700}.stop{background:#d84d4d;color:#fff}
.task{background:#f8fafc;padding:8px;margin:7px 0;border-radius:7px;cursor:pointer;border:1px solid #e1e7ef}
.task:hover,.task:focus-visible{border-color:#6f8fbf;outline:none}.task.selected{border-color:#89b4ff;box-shadow:0 0 0 2px rgba(137,180,255,.18)}
.task-status{font-weight:800}.task-blocker{color:#ffb09f;font-size:12px;margin-top:3px}
pre{white-space:pre-wrap;word-break:break-word}#dag{display:flex;flex-wrap:wrap;gap:6px}
#events{height:220px;box-sizing:border-box;margin:0;padding:10px 12px;overflow:auto;border:1px solid #e1e7ef;border-radius:8px;background:#f8fafc;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}
.node{background:#eef3f8;color:#182230;padding:5px 8px;border-radius:12px;border:1px solid #d6e0eb;font:inherit;font-weight:500;cursor:pointer}
.node:hover,.node:focus-visible{border-color:#6f8fbf;outline:none}.node.selected{border-color:#89b4ff;background:#31405a;box-shadow:0 0 0 2px rgba(137,180,255,.14)}
#dag{display:block;overflow-x:auto;padding:4px 2px 10px}.dependency-map{display:flex;align-items:flex-start;gap:28px;min-width:max-content;padding:4px 8px 16px}.dependency-stage{width:190px;position:relative}.dependency-stage h4{margin:0 0 8px;color:#64748b;font-size:11px;letter-spacing:.08em;text-transform:uppercase}.dependency-stage:not(:last-child)::after{content:'→';position:absolute;right:-23px;top:50%;color:#7b9ac0;font-size:22px;font-weight:800}.dependency-node{background:#ffffff;border:1px solid #d6e0eb;color:#182230;border-radius:8px;padding:8px;margin:6px 0;cursor:pointer;transition:transform .15s,border-color .15s,background .15s}.dependency-node:hover,.dependency-node:focus-visible{transform:translateY(-1px);border-color:#4d82c4;outline:none}.dependency-node.selected{border-color:#3578c6;background:#edf5ff;box-shadow:0 0 0 2px rgba(53,120,198,.14)}.dependency-node b{display:block;color:#1d3553;font-size:11px}.dependency-node .dep-title{margin-top:3px;line-height:1.2;color:#26384d;font-size:12px}.dependency-node .dep-meta{margin-top:5px;color:#718096;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dependency-node .dep-state{margin-top:5px;font-size:10px;font-weight:800;color:#168052}.dependency-node.blocked .dep-state{color:#bd4b3d}.dependency-node.active .dep-state{color:#2266a9}.dependency-node.ready .dep-state{color:#4c6fa3}
.live{background:#0d1015;border:1px solid #303746;border-radius:8px;padding:10px;min-height:160px;max-height:460px;overflow:auto;font:12px ui-monospace,SFMono-Regular,Consolas,monospace}
.live-line{padding:2px 0;white-space:pre-wrap;word-break:break-word}.live-error{color:#ff9b9b}.live-meta{color:#8fa3bd}.live-event{color:#d4d9e0}
.selected-label{font-size:12px;color:#3578c6;font-weight:700;margin-left:8px}.outcome{padding:9px 11px;border-radius:7px;background:#edf5ff;margin:8px 0;font-weight:650}.dag-summary{cursor:pointer;list-style:none;user-select:none}.dag-summary::-webkit-details-marker{display:none}.dag-summary::after{content:'Mở rộng';float:right;background:#eef3f8;color:#334155;border:1px solid #d6e0eb;border-radius:7px;padding:6px 10px;font-size:12px}.dag-panel[open] .dag-summary::after{content:'Thu gọn'}.dag-summary:hover::after,.dag-summary:focus-visible::after{background:#e2ebf5}.dag-summary:focus-visible{outline:2px solid #89b4ff;outline-offset:3px}.dag-summary .small{margin-left:4px}.modal-backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:22px;background:rgba(24,34,48,.38);backdrop-filter:blur(3px)}.modal-backdrop[hidden]{display:none}.modal{width:min(860px,100%);max-height:min(760px,calc(100dvh - 44px));display:flex;flex-direction:column;background:#fff;border:1px solid #cdd8e5;border-radius:12px;box-shadow:0 22px 70px rgba(24,34,48,.24);overflow:hidden}.modal-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 18px;border-bottom:1px solid #e1e7ef}.modal-title{margin:0;font-size:18px}.modal-close{background:#eef3f8;color:#334155;border:1px solid #d6e0eb;padding:7px 10px}.modal-close:hover,.modal-close:focus-visible{background:#e2ebf5;outline:2px solid #89b4ff;outline-offset:1px}.modal-body{padding:16px 18px;overflow:auto}.modal-body pre{margin:0;color:#26384d;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.modal .live{margin-top:14px;min-height:120px}
</style></head><body>
<header><div><b>CommerceOS Orchestrator</b><div id="state" class="small">Loading…</div><div id="state-pill" class="state-pill state-idle">LOADING</div></div>
<div><button id="resume">Resume</button> <button id="stop" class="stop">Stop gracefully</button></div></header>
<main><div class="cards"><div class="card">Progress<div id="progress" class="big">—</div></div><div class="card">Ready<div id="ready" class="big">—</div></div><div class="card">Builders<div id="builders" class="big">—</div></div><div class="card">Reviewers<div id="reviewers" class="big">—</div></div><div class="card">Merge<div id="merge" class="big">—</div></div><div class="card">Blocked<div id="blocked" class="big">—</div></div></div>
<div class="panel"><h3>Workflow <span class="small">Click any task card to inspect it.</span></h3><div class="lanes"><div>Ready<div id="col-ready"></div></div><div>Active<div id="col-active"></div></div><div>Review<div id="col-review"></div></div><div>Merge<div id="col-merge"></div></div><div>Blocked<div id="col-blocked"></div></div></div></div>
<details id="dag-panel" class="panel dag-panel"><summary class="dag-summary"><b>DAG / progress · Dependency sequence</b><span class="small">Read left to right. Each stage unlocks the next. Every task node is selectable.</span></summary><div id="dag"></div></details>
<div id="task-modal" class="modal-backdrop" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-header"><h3 id="modal-title" class="modal-title">Task detail <span id="selected-task" class="selected-label"></span></h3><button id="modal-close" class="modal-close" type="button" aria-label="Close task detail">Close</button></div><div class="modal-body"><div id="outcome" class="outcome">Select a task.</div><pre id="detail">Select a task.</pre></div></section></div>
<div class="panel"><h3>Live Codex activity</h3><div id="live-status" class="small">Select a task to attach the live stream.</div><div id="live" class="live"></div></div>
<div class="panel"><h3>Recent activity</h3><pre id="events"></pre></div></main>
<script>
const $=id=>document.getElementById(id);
let liveSource=null,liveTask=null,selectedTask=null,lastStatus=null;
const activeStates=['QUEUED','BUILDING','VERIFYING','FIX_REQUIRED','REVIEWING','MERGE_QUEUED','INTEGRATING'];
const terminalStates=['COMPLETED','BLOCKED','HUMAN_REQUIRED'];
const lane=t=>{const s=t.execution_state;if(['QUEUED','BUILDING','VERIFYING','FIX_REQUIRED'].includes(s))return'active';if(s==='REVIEWING')return'review';if(['MERGE_QUEUED','INTEGRATING'].includes(s))return'merge';if(['BLOCKED','HUMAN_REQUIRED'].includes(s))return'blocked';if(t.maturity==='Ready'&&t.lifecycle_state==='Backlog')return'ready';return'other'};
const repairMojibake=value=>String(value??'').replaceAll('â€™','’').replaceAll('â€œ','“').replaceAll('â€�','”').replaceAll('â€”','—').replaceAll('â€“','–').replaceAll('â€¦','…').replaceAll('â†“','↓').replaceAll('â†’','→').replaceAll('Â·','·').replaceAll('Â©','©').replaceAll('Â®','®').replaceAll('Â ',' ');
const clean=value=>repairMojibake(String(value??'').replace(/\x1b\[[0-?]*[ -\/]*[@-~]/g,'').replace(/\u001b\[[0-?]*[ -\/]*[@-~]/g,''));
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=clean(value);if(cls)e.className=cls;return e}
function stateLabel(t){return t.execution_state||((t.lifecycle_state==='Completed')?'COMPLETED':t.maturity)}
function openModal(){const modal=$('task-modal');modal.hidden=false;document.body.style.overflow='hidden';$('modal-close').focus()}
function closeModal(){const modal=$('task-modal');modal.hidden=true;document.body.style.overflow='';}
function selectTask(id){selectTaskInternal(id,true)}
function selectTaskInternal(id,showModal){if(!id)return;selectedTask=id;$('selected-task').textContent=id;if(showModal)openModal();detail(id);document.querySelectorAll('[data-task-id]').forEach(e=>{const on=e.dataset.taskId===id;e.classList.toggle('selected',on);if(e.tagName==='BUTTON')e.setAttribute('aria-pressed',String(on))})}
function card(t){const s=stateLabel(t),e=text('div','',`task ${lane(t)}${selectedTask===t.id?' selected':''}`);e.tabIndex=0;e.dataset.taskId=t.id;e.setAttribute('role','button');e.setAttribute('aria-label',`Select ${t.id}: ${t.title}`);e.append(text('b',t.id),text('div',t.title),text('div',s,'task-status'),text('div',t.blocker_code?`Blocker: ${t.blocker_code}`:`${t.domain} · attempt ${t.attempt||0}`,'small'));if(t.blocker_detail)e.append(text('div',t.blocker_detail,'task-blocker'));const open=()=>selectTask(t.id);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();open()}});return e}
function dagNode(t){const n=text('button',t.id,`node${selectedTask===t.id?' selected':''}`);n.type='button';n.dataset.taskId=t.id;n.title=`${t.title}\ndeps: ${t.depends_on.join(', ')||'none'}`;n.setAttribute('aria-label',`Select ${t.id}: ${t.title}`);n.setAttribute('aria-pressed',String(selectedTask===t.id));n.addEventListener('click',()=>selectTask(t.id));return n}
function dependencyLevel(t,byId,memo,visiting){if(memo[t.id]!==undefined)return memo[t.id];if(visiting.has(t.id))return 0;visiting.add(t.id);const deps=t.depends_on.filter(id=>byId.has(id));const level=deps.length?Math.max(...deps.map(id=>dependencyLevel(byId.get(id),byId,memo,visiting)+1)):0;visiting.delete(t.id);memo[t.id]=level;return level}
function dependencyNode(t){const s=stateLabel(t),n=document.createElement('button');n.type='button';n.className=`dependency-node ${lane(t)}${selectedTask===t.id?' selected':''}`;n.dataset.taskId=t.id;n.setAttribute('aria-pressed',String(selectedTask===t.id));n.setAttribute('aria-label',`Select ${t.id}: ${t.title}`);n.append(text('b',t.id),text('div',t.title,'dep-title'),text('div',t.depends_on.length?`needs ${t.depends_on.join(', ')}`:'no dependencies','dep-meta'),text('div',s,'dep-state'));n.addEventListener('click',()=>selectTask(t.id));return n}
function renderDependencyMap(tasks){const byId=new Map(tasks.map(t=>[t.id,t])),memo={},groups=new Map();tasks.forEach(t=>{const level=dependencyLevel(t,byId,memo,new Set());if(!groups.has(level))groups.set(level,[]);groups.get(level).push(t)});const map=document.createElement('div');map.className='dependency-map';const max=Math.max(...groups.keys(),0);for(let level=0;level<=max;level++){const stage=document.createElement('section');stage.className='dependency-stage';stage.append(text('h4',`Stage ${level+1} · ${groups.get(level)?.length||0} task(s)`));const items=document.createElement('div');(groups.get(level)||[]).sort((a,b)=>a.id.localeCompare(b.id)).forEach(t=>items.append(dependencyNode(t)));stage.append(items);map.append(stage)}$('dag').replaceChildren(map)}
function renderColumn(name,tasks){const nodes=tasks.filter(t=>lane(t)===name).map(card);$('col-'+name).replaceChildren(...(nodes.length?nodes:[text('div','None','small')]))}
function updateHeader(d){const state=d.orchestrator_state;$('state').textContent=`Orchestrator: ${state} · ${d.active_builders} builder(s) active`;$('state-pill').textContent=state;$('state-pill').className=`state-pill state-${state.toLowerCase().replaceAll('_','-')}`}
function updateOutcome(t){if(!t){$('outcome').textContent='Select a task.';return}const s=stateLabel(t);let msg=`${t.id}: ${s}`;if(s==='COMPLETED')msg+=' — task finished successfully.';else if(s==='BLOCKED'||s==='HUMAN_REQUIRED')msg+=` — action required: ${t.blocker_code||'inspect blocker detail'}.`;else if(activeStates.includes(s))msg+=' — still running.';else msg+=' — waiting for scheduler.';$('outcome').textContent=msg}
async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));lastStatus=d;updateHeader(d);$('progress').textContent=`${d.progress.completed}/${d.progress.total} (${d.progress.percent}%)`;$('ready').textContent=d.ready_frontier.length;$('builders').textContent=d.active_builders;$('reviewers').textContent=d.active_reviewers;$('merge').textContent=d.merge_queue_length;$('blocked').textContent=d.blocker_count;['ready','active','review','merge','blocked'].forEach(x=>renderColumn(x,d.tasks));renderDependencyMap(d.tasks);$('events').textContent=d.events.map(e=>`${e.created_at} ${e.task_id||'-'} ${e.kind} ${clean(e.detail)}`).join('\n');if(selectedTask&&!d.tasks.some(t=>t.id===selectedTask)){selectedTask=null;$('selected-task').textContent='';closeModal();if(liveSource){liveSource.close();liveSource=null;liveTask=null}}if(!selectedTask){const preferred=d.tasks.find(t=>activeStates.includes(t.execution_state))||d.tasks.find(t=>d.ready_frontier.includes(t.id))||d.tasks[0];if(preferred)selectTaskInternal(preferred.id,false)}else{const current=d.tasks.find(t=>t.id===selectedTask);if(current)updateOutcome(current)}}catch(e){$('state').textContent='Dashboard error: '+clean(e)}}
function summarize(r){const role=r.role||'agent';if(r.kind==='codex_started')return `● ${role} started · ${r.model} · ${r.reasoning_effort} · ${r.service_tier}`;if(r.kind==='codex_finished')return `${r.success?'✓':'✕'} ${role} finished · exit ${r.exit_code}`;if(r.kind==='codex_stderr')return `${role} warning: ${clean(r.text)}`;if(r.kind!=='codex_event')return clean(JSON.stringify(r));const e=r.event||{},i=e.item||{},p=[e.type,i.type,e.message,i.text,e.text,e.command,e.output].filter(v=>typeof v==='string'&&v.trim());return p.length?clean(p.join(' · ')):clean(JSON.stringify(e))}
function appendLive(r){const cls=r.kind==='codex_stderr'?'live-line live-error':r.kind==='codex_started'||r.kind==='codex_finished'?'live-line live-meta':'live-line live-event';$('live').append(text('div',summarize(r),cls));while($('live').childNodes.length>300)$('live').removeChild($('live').firstChild);$('live').scrollTop=$('live').scrollHeight;if(r.kind==='codex_finished')$('live-status').textContent=`Task agent finished: ${r.success?'success':'failed'} · refresh state for final result`;else if(r.at)$('live-status').textContent=`Live stream connected: ${r.task_id} · last event ${new Date(r.at).toLocaleTimeString()}`}
function watchLive(id){if(liveTask===id&&liveSource)return;if(liveSource)liveSource.close();liveTask=id;$('live').replaceChildren();$('live-status').textContent=`Connecting to task ${id}…`;liveSource=new EventSource('/api/tasks/'+encodeURIComponent(id)+'/stream');liveSource.onmessage=e=>{try{appendLive(JSON.parse(e.data))}catch(err){appendLive({kind:'codex_stderr',role:'dashboard',text:'Invalid live event: '+err})}};liveSource.onerror=()=>{const t=lastStatus?.tasks?.find(x=>x.id===id);$('live-status').textContent=t&&terminalStates.includes(t.execution_state)?`Stream closed — final task state: ${stateLabel(t)}`:`Live stream reconnecting: ${id}`};liveSource.onopen=()=>{$('live-status').textContent=`Live stream connected: ${id}`}}
async function detail(id){const r=await fetch('/api/tasks/'+encodeURIComponent(id),{cache:'no-store'});if(!r.ok){$('detail').textContent=`Unable to load ${id}`;return}const d=await r.json();updateOutcome(d);$('detail').textContent=JSON.stringify(d,null,2);watchLive(id)}
async function control(path){await fetch(path,{method:'POST'});await refresh()}
$('modal-close').addEventListener('click',closeModal);$('task-modal').addEventListener('click',e=>{if(e.target===$('task-modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('task-modal').hidden)closeModal()});$('stop').addEventListener('click',()=>control('/api/stop'));$('resume').addEventListener('click',()=>control('/api/resume'));refresh();setInterval(refresh,1500);
</script></body></html>'''
