from __future__ import annotations


DASHBOARD_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CommerceOS Orchestrator</title>
<style>
:root{color-scheme:light;--bg:#f4f7fa;--surface:#fff;--line:#d7e0e9;--text:#182636;--muted:#66778a;--accent:#2369ad;--accent-soft:#eaf3fc;--danger:#b83f3f;--radius:9px}
*{box-sizing:border-box}body{font:14px/1.45 system-ui,sans-serif;margin:0;background:var(--bg);color:var(--text)}header,main{padding:16px 22px}header{display:flex;justify-content:space-between;align-items:center;gap:18px;background:var(--surface);border-bottom:1px solid var(--line)}
.brand{display:flex;align-items:center;gap:24px}.small,.helper{font-size:12px;color:var(--muted)}.top-nav{display:flex;gap:4px}.top-nav button{background:transparent;color:#526173;border-color:transparent}.top-nav button[aria-current="page"]{background:var(--accent-soft);color:#174f86;border-color:#bad2eb}.page[hidden]{display:none}
button{min-height:38px;padding:8px 13px;border:1px solid #c4d2df;border-radius:7px;background:#e8eef4;color:#20364f;font:inherit;font-weight:750;cursor:pointer;white-space:nowrap}button:hover{background:#dce7f1}button:active{transform:translateY(1px)}button:disabled{opacity:.5;cursor:not-allowed;transform:none}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.primary{background:var(--accent);border-color:var(--accent);color:#fff}.primary:hover{background:#19588f}.danger{background:var(--danger);border-color:var(--danger);color:#fff}.danger:hover{background:#983232}
.panel,.metric{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:14px;margin-bottom:12px;box-shadow:0 2px 12px rgba(35,59,82,.05)}h2,h3{margin:0 0 8px}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.commands{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.command-status{font-weight:750;color:var(--muted)}.command-status.success{color:#17633f}.command-status.error{color:#9c3730}.output{min-height:58px;max-height:250px;overflow:auto;margin:12px 0 0;padding:10px 12px;border-radius:7px;background:#101821;color:#dbe6f0;font:12px/1.5 ui-monospace,Consolas,monospace;white-space:pre-wrap;word-break:break-word}
.metrics,.lanes{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px}.big{font-size:24px;font-weight:850}.state-pill{display:inline-block;margin-top:5px;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:800;background:#e8edf3;color:#526173}.state-running{background:#dff6e9;color:#12633f}.state-finished{background:#e3f0ff;color:#1d5b91}.state-blocked,.state-human-required{background:#ffe7e2;color:#a43f32}.state-stopping,.state-force-stopping{background:#fff1cc;color:#8a5a00}
.task{padding:8px;margin:7px 0;border:1px solid #dfe6ee;border-radius:7px;background:#f8fafc;cursor:pointer}.task:hover,.task:focus-visible,.task.selected{border-color:#5489c4;outline:none}.task-status{font-weight:800}.task-blocker{color:#a43f32;font-size:12px}.dag-panel{min-width:0;max-width:100%;overflow:hidden}.dag-summary{cursor:pointer;list-style:none}.dag-summary::-webkit-details-marker{display:none}.dag-summary::after{content:'Expand';float:right}.dag-panel[open] .dag-summary::after{content:'Collapse'}#dag{min-width:0;max-width:100%;overflow-x:auto;overscroll-behavior-inline:contain}.dependency-map{display:flex;width:max-content;min-width:100%;gap:24px;padding:12px 4px}.dependency-stage{flex:0 0 190px;min-width:0}.dependency-stage h4{margin:0 0 7px;color:var(--muted);font-size:11px;text-transform:uppercase}.dependency-node{display:block;width:100%;text-align:left;margin:6px 0;background:#fff}.dependency-node b,.dependency-node span{display:block}.dep-title{font-size:12px;overflow-wrap:anywhere;white-space:normal}.dep-state{margin-top:4px;color:#17633f;font-size:11px;font-weight:800}
.live{min-height:150px;max-height:430px;overflow:auto;padding:10px;border-radius:7px;background:#101318;color:#d4d9e0;font:12px/1.45 ui-monospace,Consolas,monospace}.live-line{padding:2px 0;white-space:pre-wrap;word-break:break-word}.live-error{color:#ff9b9b}.live-meta{color:#9fb7d2}#events{height:210px;margin:0;overflow:auto;white-space:pre-wrap}
.settings-layout{display:grid;grid-template-columns:minmax(220px,.7fr) minmax(0,1.7fr);gap:12px}.field,.role-field{display:grid;gap:5px;margin-bottom:12px}.field label,.role-field label,.field-label{font-size:12px;font-weight:800;color:#405269}.field input,.field select,.role-field input,.role-field select{width:100%;min-height:40px;padding:8px 10px;border:1px solid #b8c8d7;border-radius:7px;background:#fff;color:var(--text)}.check{display:flex;align-items:flex-start;gap:8px}.check input{width:18px;height:18px;margin-top:2px}.check .field-label,.check .helper{display:block}.role-list,.capabilities{display:grid;gap:9px}.role-row{display:grid;grid-template-columns:145px 140px minmax(180px,1fr);gap:9px;align-items:end;padding:12px;border:1px solid var(--line);border-radius:var(--radius);background:#fbfcfe}.role-name{align-self:center}.provider-state,.sandbox-state{margin-top:4px;font-size:11px;color:var(--muted)}.provider-state.error,.sandbox-state.error{color:#a43f32}.capability{padding:8px 0;border-bottom:1px solid #e3e9ef}.capability code{font-size:11px;word-break:break-all}.settings-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.notice{margin-top:12px;padding:10px 12px;border:1px solid #efd28a;border-radius:7px;background:#fff4d5;color:#75500b}.notice.success{border-color:#b9dfc8;background:#e6f5ec;color:#145d3c}.notice.error{border-color:#edbeb5;background:#ffebe7;color:#96372d}
.modal-backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:rgba(24,34,48,.4);backdrop-filter:blur(3px)}.modal-backdrop[hidden]{display:none}.modal{width:min(850px,100%);max-height:calc(100dvh - 40px);display:flex;flex-direction:column;overflow:hidden;border-radius:11px;background:#fff}.modal-header{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid var(--line)}.modal-body{padding:16px;overflow:auto}.modal-body pre{white-space:pre-wrap;word-break:break-word}.outcome{padding:9px 11px;border-radius:7px;background:var(--accent-soft)}
@media(max-width:820px){header{align-items:flex-start}.brand{display:grid;gap:10px}.settings-layout{grid-template-columns:1fr}.role-row{grid-template-columns:1fr 1fr}.role-name{grid-column:1/-1}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.head{display:grid}}
@media(max-width:520px){header,main{padding:13px}.top-nav{width:100%}.top-nav button{flex:1}.lanes,.role-row{grid-template-columns:1fr}.commands button{flex:1 1 44%}.modal-backdrop{padding:8px}}
</style></head><body>
<header><div class="brand"><div><b>CommerceOS Orchestrator</b><div id="state" class="small">Loading...</div><div id="state-pill" class="state-pill">LOADING</div></div><nav class="top-nav" aria-label="Main navigation"><button type="button" data-page="dashboard" aria-current="page">Dashboard</button><button type="button" data-page="settings">Settings</button></nav></div></header>
<main>
<section id="dashboard-page" class="page">
<section class="panel" aria-labelledby="commands-title"><div class="head"><div><h2 id="commands-title">Commands</h2><div class="small">Graceful Stop drains active work. Force Stop kills only the registered worker tree and preserves task worktrees for Resume. Cleanup removes terminal-task worktrees.</div></div><div id="command-status" class="command-status" role="status">Ready</div></div><div class="commands"><button id="refresh" type="button">Refresh status</button><button data-action="validate" type="button">Validate</button><button data-action="plan" type="button">Plan</button><button data-action="dry-run" type="button">Dry run</button><button data-action="run" class="primary" type="button">Run</button><button data-action="start" type="button">Start</button><button data-action="resume" type="button">Resume</button><button data-action="stop" type="button">Stop gracefully</button><button data-action="force-stop" class="danger" type="button">Force Stop now</button><button data-action="cleanup" type="button">Cleanup terminal worktrees</button></div><pre id="command-output" class="output">Choose a command to see its result.</pre></section>
<div class="metrics"><div class="metric">Progress<div id="progress" class="big">-</div></div><div class="metric">Ready<div id="ready" class="big">-</div></div><div class="metric">Builders<div id="builders" class="big">-</div></div><div class="metric">Reviewers<div id="reviewers" class="big">-</div></div><div class="metric">Merge<div id="merge" class="big">-</div></div><div class="metric">Blocked<div id="blocked" class="big">-</div></div></div>
<section class="panel"><h3>Workflow <span class="small">Click any task card to inspect it.</span></h3><div class="lanes"><div>Ready<div id="col-ready"></div></div><div>Active<div id="col-active"></div></div><div>Review<div id="col-review"></div></div><div>Merge<div id="col-merge"></div></div><div>Blocked<div id="col-blocked"></div></div></div></section>
<details class="panel dag-panel"><summary class="dag-summary"><b>DAG / progress</b><span class="small"> Dependency sequence. Every task node is selectable.</span></summary><div id="dag"></div></details>
<section class="panel"><h3>Live agent activity</h3><div id="live-status" class="small">Select a task to attach the live stream.</div><div id="live" class="live"></div></section>
<section class="panel"><h3>Recent activity</h3><pre id="events"></pre></section>
</section>
<section id="settings-page" class="page" hidden>
<section class="panel head"><div><h2>Agent settings</h2><div class="small">Choose a provider and model per role. Provider credentials never enter CommerceOS.</div></div><div id="settings-status" class="command-status" role="status">Loading settings...</div></section>
<div class="settings-layout"><section class="panel"><h3>Runtime defaults</h3><div class="field"><label for="setting-catalog">Task catalog</label><select id="setting-catalog"><option value="commerceos">CommerceOS product</option><option value="orchestrator">Orchestrator tooling</option></select><div class="helper">Applied after restarting this dashboard.</div></div><div class="field"><label for="setting-builders">Maximum Builders</label><input id="setting-builders" type="number" min="1" max="2" inputmode="numeric"></div><div class="field"><label for="setting-fixes">Maximum fix attempts</label><input id="setting-fixes" type="number" min="0" max="10" inputmode="numeric"></div><label class="check" for="setting-cloud"><input id="setting-cloud" type="checkbox"><span><span class="field-label">Allow infrastructure verification</span><span class="helper">LocalStack only under ADR-012. This never authorizes real AWS.</span></span></label><h3>Detected providers</h3><div id="capabilities" class="capabilities"></div></section>
<section class="panel"><h3>Role profiles</h3><div class="helper">Planning covers Backlog Planner, Domain Architect, and Technical Architect. Unsupported combinations are disabled.</div><div id="role-list" class="role-list"></div><div class="settings-actions"><button id="save-settings" class="primary" type="button">Save settings</button><button id="reset-settings" type="button">Restore defaults</button></div><div id="settings-notice" class="notice" hidden></div></section></div>
</section>
</main>
<div id="task-modal" class="modal-backdrop" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-header"><h3 id="modal-title">Task detail <span id="selected-task" class="small"></span></h3><button id="modal-close" type="button" aria-label="Close task detail">Close</button></div><div class="modal-body"><div id="outcome" class="outcome">Select a task.</div><pre id="detail">Select a task.</pre></div></section></div>
<script>
const $=id=>document.getElementById(id),headers={'X-CommerceOS-Dashboard':'1'};
let liveSource=null,liveTask=null,selectedTask=null,lastStatus=null,settingsView=null;
const activeStates=['QUEUED','PLANNING','INITIAL_BUILD','PRE_REVIEW_VERIFICATION','REPAIR_REQUIRED','REPAIR_BUILD','REPAIR_VERIFICATION','FIRST_REVIEW','RE_REVIEW','MERGE_QUEUED','INTEGRATING','FINALIZING'];
const terminalStates=['PLANNING_COMPLETED','COMPLETED','PLANNING_REQUIRED','ORCHESTRATOR_ACTION_REQUIRED','BLOCKED','HUMAN_REQUIRED'];
const roleLabels={planning:'Planning',builder:'Builder',reviewer:'Reviewer',conflict_resolver:'Conflict Resolver'};
const clean=value=>String(value??'').replace(/\x1b\[[0-?]*[ -\/]*[@-~]/g,'');
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=clean(value);if(cls)e.className=cls;return e}
function lane(t){const s=t.execution_state;if(['QUEUED','PLANNING','INITIAL_BUILD','PRE_REVIEW_VERIFICATION','REPAIR_REQUIRED','REPAIR_BUILD','REPAIR_VERIFICATION'].includes(s))return'active';if(['FIRST_REVIEW','RE_REVIEW'].includes(s))return'review';if(['MERGE_QUEUED','INTEGRATING','FINALIZING'].includes(s))return'merge';if(['PLANNING_REQUIRED','ORCHESTRATOR_ACTION_REQUIRED','BLOCKED','HUMAN_REQUIRED'].includes(s))return'blocked';if(t.maturity==='Ready'&&t.lifecycle_state==='Backlog')return'ready';return'other'}
function stateLabel(t){return t.execution_state||(t.lifecycle_state==='Completed'?'COMPLETED':t.maturity)}
function openModal(){ $('task-modal').hidden=false;document.body.style.overflow='hidden';$('modal-close').focus() }
function closeModal(){ $('task-modal').hidden=true;document.body.style.overflow='' }
function selectTask(id){selectedTask=id;$('selected-task').textContent=id;openModal();detail(id);document.querySelectorAll('[data-task-id]').forEach(e=>e.classList.toggle('selected',e.dataset.taskId===id))}
function card(t){const e=text('div','',`task ${lane(t)}`);e.tabIndex=0;e.dataset.taskId=t.id;e.setAttribute('role','button');e.setAttribute('aria-label',`Select ${t.id}: ${t.title}`);e.append(text('b',t.id),text('div',t.title),text('div',stateLabel(t),'task-status'),text('div',`${t.domain} | attempt ${t.attempt||0}`,'small'));if(t.current_actor)e.append(text('div',`Owner: ${t.current_actor}`,'small'));if(t.next_transition_condition)e.append(text('div',`Next: ${t.next_transition_condition}`,'small'));const open=()=>selectTask(t.id);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();open()}});return e}
function renderColumn(name,tasks){const nodes=tasks.filter(t=>lane(t)===name).map(card);$('col-'+name).replaceChildren(...(nodes.length?nodes:[text('div','None','small')]))}
function dependencyLevel(t,byId,memo,visiting){if(memo[t.id]!==undefined)return memo[t.id];if(visiting.has(t.id))return 0;visiting.add(t.id);const deps=t.depends_on.filter(id=>byId.has(id)),level=deps.length?Math.max(...deps.map(id=>dependencyLevel(byId.get(id),byId,memo,visiting)+1)):0;visiting.delete(t.id);memo[t.id]=level;return level}
function dependencyNode(t){const n=document.createElement('button');n.type='button';n.className='dependency-node';n.dataset.taskId=t.id;n.setAttribute('aria-label',`Select ${t.id}: ${t.title}`);n.append(text('b',t.id),text('span',t.title,'dep-title'),text('span',stateLabel(t),'dep-state'));n.addEventListener('click',()=>selectTask(t.id));return n}
function renderDependencyMap(tasks){const byId=new Map(tasks.map(t=>[t.id,t])),memo={},groups=new Map();tasks.forEach(t=>{const level=dependencyLevel(t,byId,memo,new Set());if(!groups.has(level))groups.set(level,[]);groups.get(level).push(t)});const map=document.createElement('div');map.className='dependency-map';for(let level=0;level<=Math.max(...groups.keys(),0);level++){const stage=document.createElement('section');stage.className='dependency-stage';stage.append(text('h4',`Stage ${level+1} | ${groups.get(level)?.length||0} tasks`));(groups.get(level)||[]).sort((a,b)=>a.id.localeCompare(b.id)).forEach(t=>stage.append(dependencyNode(t)));map.append(stage)}$('dag').replaceChildren(map)}
function updateOutcome(t){if(!t)return;$('outcome').textContent=`${t.id}: ${stateLabel(t)}${activeStates.includes(stateLabel(t))?' - still running.':''}`}
async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));lastStatus=d;const worker=d.worker||{state:'UNKNOWN',pid:null};$('state').textContent=`Catalog: ${d.catalog} | Orchestrator: ${d.orchestrator_state} | Worker: ${worker.state}${worker.pid?' #'+worker.pid:''} | ${d.active_builders} Builders active`;$('state-pill').textContent=d.orchestrator_state;$('state-pill').className=`state-pill state-${d.orchestrator_state.toLowerCase().replaceAll('_','-')}`;$('progress').textContent=`${d.progress.completed}/${d.progress.total} (${d.progress.percent}%)`;$('ready').textContent=d.ready_frontier.length;$('builders').textContent=d.active_builders;$('reviewers').textContent=d.active_reviewers;$('merge').textContent=d.merge_queue_length;$('blocked').textContent=d.blocker_count;['ready','active','review','merge','blocked'].forEach(x=>renderColumn(x,d.tasks));renderDependencyMap(d.tasks);$('events').textContent=d.events.map(e=>`${e.created_at} ${e.task_id||'-'} ${e.kind} ${clean(e.detail)}`).join('\n');if(!selectedTask){const preferred=d.tasks.find(t=>activeStates.includes(t.execution_state))||d.tasks.find(t=>d.ready_frontier.includes(t.id));if(preferred)selectedTask=preferred.id}}catch(e){$('state').textContent='Dashboard error: '+clean(e)}}
function summarize(r){const provider=r.provider||'codex',role=r.role||'agent';if(r.kind==='codex_started')return `${provider} ${role} started | ${r.model||'provider default'} | ${r.reasoning_effort} | ${r.service_tier} | ${r.sandbox}`;if(r.kind==='codex_finished')return `${provider} ${role} finished | exit ${r.exit_code}`;if(r.kind==='codex_stderr')return `${provider} ${role} warning: ${clean(r.text)}`;const e=r.event||{},i=e.item||{},parts=[e.type,i.type,e.message,i.text,e.text,e.command,e.output].filter(v=>typeof v==='string'&&v.trim());return parts.length?clean(parts.join(' | ')):clean(JSON.stringify(e))}
function appendLive(r){const cls=r.kind==='codex_stderr'?'live-line live-error':r.kind==='codex_started'||r.kind==='codex_finished'?'live-line live-meta':'live-line';$('live').append(text('div',summarize(r),cls));while($('live').childNodes.length>300)$('live').firstChild.remove();$('live').scrollTop=$('live').scrollHeight}
function watchLive(id){if(liveTask===id&&liveSource)return;if(liveSource)liveSource.close();liveTask=id;$('live').replaceChildren();$('live-status').textContent=`Connecting to ${id}...`;liveSource=new EventSource('/api/tasks/'+encodeURIComponent(id)+'/stream');liveSource.onmessage=e=>{try{appendLive(JSON.parse(e.data))}catch(err){appendLive({kind:'codex_stderr',provider:'dashboard',text:String(err)})}};liveSource.onerror=()=>{const t=lastStatus?.tasks?.find(x=>x.id===id);$('live-status').textContent=t&&terminalStates.includes(t.execution_state)?`Stream closed - ${stateLabel(t)}`:`Live stream reconnecting: ${id}`};liveSource.onopen=()=>{$('live-status').textContent=`Live stream connected: ${id}`}}
async function detail(id){const r=await fetch('/api/tasks/'+encodeURIComponent(id),{cache:'no-store'});if(!r.ok){$('detail').textContent=`Unable to load ${id}`;return}const d=await r.json();updateOutcome(d);$('detail').textContent=JSON.stringify(d,null,2);watchLive(id)}
function setCommandBusy(busy){document.querySelectorAll('[data-action]').forEach(b=>b.disabled=busy);if(busy)$('command-status').textContent='Running command...'}
async function runAction(action){if(action==='cleanup'&&!window.confirm('Remove worktrees for terminal tasks? Active work is never removed.'))return;if(action==='force-stop'&&!window.confirm('Immediately terminate the registered Orchestrator worker and its child tools? Task state and worktrees will be preserved so Resume can run the current stage again.'))return;setCommandBusy(true);try{const r=await fetch('/api/actions/'+encodeURIComponent(action),{method:'POST',headers}),d=await r.json();$('command-output').textContent=JSON.stringify(d,null,2);const candidate=action==='plan'&&d.planning_candidate?.task;$('command-status').textContent=r.ok?(candidate?`Planning candidate: ${candidate}. Use Run or Start to launch Planner.`:`${action} finished`):`${action} failed`;$('command-status').className=`command-status ${r.ok?'success':'error'}`;await refresh()}catch(e){$('command-output').textContent=clean(e);$('command-status').textContent=`${action} failed`;$('command-status').className='command-status error'}finally{setCommandBusy(false)}}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==name+'-page');document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===name?'page':'false'));if(name==='settings')loadSettings();location.hash=name==='settings'?'settings':''}
function selectControl(id,values,current){const s=document.createElement('select');s.id=id;values.forEach(value=>{const o=text('option',value);o.value=value;o.selected=value===current;s.append(o)});return s}
function roleField(label,control){const wrap=document.createElement('div');wrap.className='role-field';const lab=text('label',label);lab.htmlFor=control.id;wrap.append(lab,control);return wrap}
function renderCapabilities(caps){$('capabilities').replaceChildren(...Object.entries(caps).map(([name,cap])=>{const item=document.createElement('div');item.className='capability';item.append(text('b',`${name}: ${cap.available?'available':'not found'}`),text('div',cap.version?`Version ${cap.version}`:'Version unavailable','helper'),text('code',cap.executable||'No executable detected'));return item}))}
function syncRole(row,role,providerChanged=false){const provider=row.querySelector('[data-field="provider"]'),cap=settingsView.capabilities[provider.value],supported=cap.available&&cap.supported_roles.includes(role),model=row.querySelector('[data-field="model"]'),list=row.querySelector('datalist'),sandbox=row.querySelector('[data-field="sandbox_mode"]');model.disabled=!supported;list.replaceChildren(...(cap.models||[]).map(item=>{const option=document.createElement('option');option.value=item.id;option.label=item.label;return option}));if(providerChanged&&provider.value==='antigravity'){if(cap.models?.length&&!cap.models.some(item=>item.id===model.value))model.value=cap.models[0].id;sandbox.value=role==='reviewer'?'read-only':'workspace-write'}row.querySelector('[data-field="reasoning_effort"]').disabled=!cap.supports_reasoning_effort||!supported;row.querySelector('[data-field="service_tier"]').disabled=!cap.supports_service_tier||!supported;sandbox.disabled=role==='reviewer'||!cap.supports_sandbox_mode||!supported;const sandboxState=row.querySelector('.sandbox-state');sandboxState.textContent=role==='reviewer'?'Reviewer is always read-only.':provider.value==='antigravity'?'Managed by Antigravity.':sandbox.value==='danger-full-access'?'Full machine access. Use only for trusted local tasks.':'Writes are limited to the task workspace.';sandboxState.className=`sandbox-state${sandbox.value==='danger-full-access'?' error':''}`;const state=row.querySelector('.provider-state');state.textContent=supported?(provider.value==='antigravity'?`${cap.models?.length||0} detected models. Leave blank for the provider default.`:'Role contract supported.'):'This provider cannot preserve the role contract.';state.className=`provider-state${supported?'':' error'}`;$('save-settings').disabled=Boolean(document.querySelector('.provider-state.error'))}
function renderRoles(settings){const rows=Object.entries(settings.profiles).map(([role,p])=>{const row=document.createElement('section');row.className='role-row';row.dataset.role=role;const name=document.createElement('div');name.className='role-name';name.append(text('b',roleLabels[role]),text('div',role==='planning'?'Planner and architects':role.replaceAll('_',' '),'helper'));const provider=selectControl(`provider-${role}`,Object.keys(settingsView.capabilities),p.provider);provider.dataset.field='provider';Array.from(provider.options).forEach(o=>{const cap=settingsView.capabilities[o.value];o.disabled=!cap.available||!cap.supported_roles.includes(role)});const model=document.createElement('input'),modelList=document.createElement('datalist');model.id=`model-${role}`;modelList.id=`models-${role}`;model.setAttribute('list',modelList.id);model.value=p.model;model.maxLength=100;model.autocomplete='off';model.dataset.field='model';const reasoning=selectControl(`reasoning-${role}`,['low','medium','high','xhigh'],p.reasoning_effort);reasoning.dataset.field='reasoning_effort';const service=selectControl(`service-${role}`,['standard','priority'],p.service_tier);service.dataset.field='service_tier';const sandbox=selectControl(`sandbox-${role}`,role==='reviewer'?['read-only']:['workspace-write','danger-full-access'],p.sandbox_mode);sandbox.dataset.field='sandbox_mode';const modelWrap=roleField('Model',model);modelWrap.append(modelList,text('div','', 'provider-state'));const sandboxWrap=roleField('Sandbox',sandbox);sandboxWrap.append(text('div','', 'sandbox-state'));row.append(name,roleField('Provider',provider),modelWrap,roleField('Reasoning',reasoning),roleField('Service',service),sandboxWrap);provider.addEventListener('change',()=>syncRole(row,role,true));sandbox.addEventListener('change',()=>syncRole(row,role));return row});$('role-list').replaceChildren(...rows);rows.forEach(row=>syncRole(row,row.dataset.role))}
async function loadSettings(){try{const r=await fetch('/api/settings',{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(JSON.stringify(v));settingsView=v;const s=v.settings;$('setting-catalog').value=s.catalog;$('setting-builders').value=s.max_builders;$('setting-fixes').value=s.max_fix_attempts;$('setting-cloud').checked=s.allow_cloud;renderCapabilities(v.capabilities);renderRoles(s);$('settings-status').textContent=v.restart_required?'Restart required':'Settings loaded';$('settings-status').className=`command-status ${v.restart_required?'error':'success'}`;$('settings-notice').hidden=!v.restart_required;if(v.restart_required){$('settings-notice').textContent='Restart the dashboard to apply saved settings.';$('settings-notice').className='notice'}}catch(e){$('settings-status').textContent='Unable to load settings';$('settings-status').className='command-status error';$('settings-notice').hidden=false;$('settings-notice').textContent=clean(e);$('settings-notice').className='notice error'}}
function collectSettings(){const profiles={};document.querySelectorAll('.role-row').forEach(row=>{const get=name=>row.querySelector(`[data-field="${name}"]`).value;profiles[row.dataset.role]={provider:get('provider'),model:get('model').trim(),reasoning_effort:get('reasoning_effort'),service_tier:get('service_tier'),sandbox_mode:get('sandbox_mode')}});return{schema_version:1,catalog:$('setting-catalog').value,max_builders:Number($('setting-builders').value),max_fix_attempts:Number($('setting-fixes').value),allow_cloud:$('setting-cloud').checked,profiles}}
async function saveSettings(){try{const r=await fetch('/api/settings',{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(collectSettings())}),d=await r.json();if(!r.ok)throw Error(d.detail||JSON.stringify(d));await loadSettings();$('settings-notice').hidden=false;$('settings-notice').className='notice success';$('settings-notice').textContent=d.restart_required?'Saved. Restart the dashboard to apply settings.':'Saved and active.'}catch(e){$('settings-notice').hidden=false;$('settings-notice').className='notice error';$('settings-notice').textContent=clean(e)}}
async function resetSettings(){try{const r=await fetch('/api/settings/reset',{method:'POST',headers}),d=await r.json();if(!r.ok)throw Error(d.detail||JSON.stringify(d));await loadSettings();$('settings-notice').hidden=false;$('settings-notice').className='notice success';$('settings-notice').textContent='Repository defaults restored.'}catch(e){$('settings-notice').hidden=false;$('settings-notice').className='notice error';$('settings-notice').textContent=clean(e)}}
$('modal-close').addEventListener('click',closeModal);$('task-modal').addEventListener('click',e=>{if(e.target===$('task-modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('task-modal').hidden)closeModal()});document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>runAction(b.dataset.action)));document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('refresh').addEventListener('click',refresh);$('save-settings').addEventListener('click',saveSettings);$('reset-settings').addEventListener('click',resetSettings);showPage(location.hash==='#settings'?'settings':'dashboard');refresh();setInterval(refresh,1500);
</script></body></html>'''
