from __future__ import annotations

DASHBOARD_HTML = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CommerceOS Orchestrator</title>
<style>body{font:14px system-ui;margin:0;background:#11151b;color:#e8ebf0}header,main{padding:16px 22px}header{display:flex;justify-content:space-between;background:#181d25}.cards,.lanes{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card,.panel{background:#181d25;border:1px solid #303746;border-radius:10px;padding:12px;margin-bottom:12px}.big{font-size:24px;font-weight:800}.task{background:#232a35;padding:8px;margin:7px 0;border-radius:7px;cursor:pointer}.small{font-size:12px;color:#a8b0bd}button{padding:9px 14px;border:0;border-radius:7px;font-weight:700}.stop{background:#d84d4d;color:#fff}pre{white-space:pre-wrap;word-break:break-word}#dag{display:flex;flex-wrap:wrap;gap:6px}.node{background:#252d39;padding:5px 8px;border-radius:12px}.live{background:#0d1015;border:1px solid #303746;border-radius:8px;padding:10px;min-height:160px;max-height:460px;overflow:auto;font:12px ui-monospace,SFMono-Regular,Consolas,monospace}.live-line{padding:2px 0;white-space:pre-wrap;word-break:break-word}.live-error{color:#ff9b9b}.live-meta{color:#8fa3bd}</style></head><body>
<header><div><b>CommerceOS Orchestrator</b><div id="state" class="small">Loading…</div></div><div><button id="resume">Resume</button> <button id="stop" class="stop">Stop gracefully</button></div></header>
<main><div class="cards"><div class="card">Progress<div id="progress" class="big">—</div></div><div class="card">Ready<div id="ready" class="big">—</div></div><div class="card">Builders<div id="builders" class="big">—</div></div><div class="card">Reviewers<div id="reviewers" class="big">—</div></div><div class="card">Merge<div id="merge" class="big">—</div></div><div class="card">Blocked<div id="blocked" class="big">—</div></div></div>
<div class="panel"><h3>Workflow</h3><div class="lanes"><div>Ready<div id="col-ready"></div></div><div>Active<div id="col-active"></div></div><div>Review<div id="col-review"></div></div><div>Merge<div id="col-merge"></div></div><div>Blocked<div id="col-blocked"></div></div></div></div>
<div class="panel"><h3>DAG / progress</h3><div id="dag"></div></div><div class="panel"><h3>Task detail</h3><pre id="detail">Select a task.</pre></div><div class="panel"><h3>Live Codex activity</h3><div id="live-status" class="small">Select a task to attach the live stream.</div><div id="live" class="live"></div></div><div class="panel"><h3>Recent activity</h3><pre id="events"></pre></div></main>
<script>
const $=id=>document.getElementById(id);let liveSource=null,liveTask=null;const lane=t=>{const s=t.execution_state;if(['QUEUED','BUILDING','VERIFYING','FIX_REQUIRED'].includes(s))return'active';if(s==='REVIEWING')return'review';if(['MERGE_QUEUED','INTEGRATING'].includes(s))return'merge';if(['BLOCKED','HUMAN_REQUIRED'].includes(s))return'blocked';if(t.maturity==='Ready'&&t.lifecycle_state==='Backlog')return'ready';return'other'};
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=String(value??'');if(cls)e.className=cls;return e}function card(t){const e=text('div','',`task ${lane(t)}`);e.tabIndex=0;e.append(text('b',t.id),text('div',t.title),text('div',`${t.execution_state||t.maturity} · ${t.domain}`,'small'));const open=()=>detail(t.id);e.addEventListener('click',open);e.addEventListener('keydown',x=>{if(x.key==='Enter'){x.preventDefault();open()}});return e}
function renderColumn(name,tasks){const nodes=tasks.filter(t=>lane(t)===name).map(card);$("col-"+name).replaceChildren(...(nodes.length?nodes:[text('div','None','small')]))}async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));$('state').textContent=`State: ${d.orchestrator_state}`;$('progress').textContent=`${d.progress.completed}/${d.progress.total} (${d.progress.percent}%)`;$('ready').textContent=d.ready_frontier.length;$('builders').textContent=d.active_builders;$('reviewers').textContent=d.active_reviewers;$('merge').textContent=d.merge_queue_length;$('blocked').textContent=d.blocker_count;['ready','active','review','merge','blocked'].forEach(x=>renderColumn(x,d.tasks));$('dag').replaceChildren(...d.tasks.map(t=>{const n=text('span',t.id,'node');n.title=`deps: ${t.depends_on.join(', ')}`;return n}));$('events').textContent=d.events.map(e=>`${e.created_at} ${e.task_id||'-'} ${e.kind} ${e.detail}`).join('\n')}catch(e){$('state').textContent='Dashboard error: '+e}}
function summarize(r){const role=r.role||'agent';if(r.kind==='codex_started')return `● ${role} · ${r.model} · ${r.reasoning_effort} · ${r.service_tier}`;if(r.kind==='codex_finished')return `${r.success?'✓':'✕'} ${role} finished · exit ${r.exit_code}`;if(r.kind==='codex_stderr')return `${role} stderr: ${r.text}`;if(r.kind!=='codex_event')return JSON.stringify(r);const e=r.event||{},i=e.item||{},p=[e.type,i.type,e.message,i.text,e.text,e.command,e.output].filter(v=>typeof v==='string'&&v.trim());return p.length?p.join(' · '):JSON.stringify(e)}
function appendLive(r){const cls=r.kind==='codex_stderr'?'live-line live-error':r.kind==='codex_started'||r.kind==='codex_finished'?'live-line live-meta':'live-line';$('live').append(text('div',summarize(r),cls));while($('live').childNodes.length>300)$('live').removeChild($('live').firstChild);$('live').scrollTop=$('live').scrollHeight}
function watchLive(id){if(liveTask===id&&liveSource)return;if(liveSource)liveSource.close();liveTask=id;$('live').replaceChildren();$('live-status').textContent=`Live stream: ${id}`;liveSource=new EventSource('/api/tasks/'+encodeURIComponent(id)+'/stream');liveSource.onmessage=e=>{try{appendLive(JSON.parse(e.data))}catch(err){appendLive({kind:'codex_stderr',role:'dashboard',text:'Invalid live event: '+err})}};liveSource.onerror=()=>{$('live-status').textContent=`Live stream reconnecting: ${id}`};liveSource.onopen=()=>{$('live-status').textContent=`Live stream connected: ${id}`}}
async function detail(id){const r=await fetch('/api/tasks/'+encodeURIComponent(id));$('detail').textContent=JSON.stringify(await r.json(),null,2);watchLive(id)}async function control(path){await fetch(path,{method:'POST'});await refresh()}$('stop').addEventListener('click',()=>control('/api/stop'));$('resume').addEventListener('click',()=>control('/api/resume'));refresh();setInterval(refresh,1500);
</script></body></html>'''
