using System.Globalization;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using CommerceOS.Notification.Application;
using CommerceOS.Notification.Domain;

namespace CommerceOS.Notification.Infrastructure.Persistence;

public sealed record DynamoDbNotificationOptions(string TableName);
/// <summary>Recipient is part of every key; no shared tenant read/acknowledgement state exists.</summary>
public sealed class DynamoDbNotificationStore(IAmazonDynamoDB client, DynamoDbNotificationOptions options) : INotificationStore
{
    public async Task<TenantNotification?> GetAsync(string trustedTenantId, string notificationId, string recipientId, CancellationToken ct) { var result = await client.GetItemAsync(new() { TableName = options.TableName, ConsistentRead = true, Key = Key(trustedTenantId, notificationId, recipientId) }, ct); return result.Item.Count == 0 ? null : Read(result.Item); }
    public async Task<NotificationOutcome> CreateAsync(TenantNotification notification, CancellationToken ct) { try { await client.TransactWriteItemsAsync(new() { TransactItems = [new() { Put = new() { TableName = options.TableName, Item = Item(notification), ConditionExpression = "attribute_not_exists(PK)" } }, new() { Put = new() { TableName = options.TableName, Item = new() { ["PK"] = S($"TENANT#{E(notification.TenantId)}"), ["SK"] = S($"SOURCE#{E(notification.SourceIdentity)}#{E(notification.RecipientId)}"), ["NotificationId"] = S(notification.Id) }, ConditionExpression = "attribute_not_exists(PK)" } }] }, ct); return NotificationOutcome.Applied; } catch (TransactionCanceledException) { return NotificationOutcome.AlreadyApplied; } }
    public async Task<NotificationOutcome> SaveAsync(TenantNotification before, TenantNotification after, CancellationToken ct) { if (before.TenantId != after.TenantId || before.Id != after.Id || before.RecipientId != after.RecipientId) return NotificationOutcome.Forbidden; try { await client.PutItemAsync(new() { TableName = options.TableName, Item = Item(after), ConditionExpression = "#state = :state", ExpressionAttributeNames = new() { ["#state"] = "State" }, ExpressionAttributeValues = new() { [":state"] = S(before.State.ToString()) } }, ct); return NotificationOutcome.Applied; } catch (ConditionalCheckFailedException) { return NotificationOutcome.AlreadyApplied; } }
    public async Task<IReadOnlyList<TenantNotification>> ListAsync(string trustedTenantId, string recipientId, int pageSize, CancellationToken ct) { var result = await client.QueryAsync(new() { TableName = options.TableName, KeyConditionExpression = "PK = :pk AND begins_with(SK, :prefix)", ExpressionAttributeValues = new() { [":pk"] = S($"TENANT#{E(trustedTenantId)}"), [":prefix"] = S($"NOTIFICATION#{E(recipientId)}#") }, Limit = pageSize, ScanIndexForward = false }, ct); return result.Items.Select(Read).ToArray(); }
    private static Dictionary<string, AttributeValue> Key(string tenant, string id, string recipient) => new() { ["PK"] = S($"TENANT#{E(tenant)}"), ["SK"] = S($"NOTIFICATION#{E(recipient)}#{E(id)}") };
    private static Dictionary<string, AttributeValue> Item(TenantNotification x) => new() { ["PK"] = S($"TENANT#{E(x.TenantId)}"), ["SK"] = S($"NOTIFICATION#{E(x.RecipientId)}#{E(x.Id)}"), ["Id"] = S(x.Id), ["TenantId"] = S(x.TenantId), ["RecipientId"] = S(x.RecipientId), ["SourceIdentity"] = S(x.SourceIdentity), ["Summary"] = S(x.Summary), ["IsActionable"] = new() { BOOL = x.IsActionable }, ["State"] = S(x.State.ToString()), ["CreatedAt"] = S(x.CreatedAt.ToString("O", CultureInfo.InvariantCulture)), ["ReadAt"] = S(x.ReadAt?.ToString("O", CultureInfo.InvariantCulture) ?? string.Empty), ["AcknowledgedAt"] = S(x.AcknowledgedAt?.ToString("O", CultureInfo.InvariantCulture) ?? string.Empty) };
    private static TenantNotification Read(Dictionary<string, AttributeValue> x) => new(x["Id"].S, x["TenantId"].S, x["RecipientId"].S, x["SourceIdentity"].S, x["Summary"].S, x["IsActionable"].BOOL == true, Enum.Parse<NotificationState>(x["State"].S), DateTimeOffset.Parse(x["CreatedAt"].S, CultureInfo.InvariantCulture), string.IsNullOrEmpty(x["ReadAt"].S) ? null : DateTimeOffset.Parse(x["ReadAt"].S, CultureInfo.InvariantCulture), string.IsNullOrEmpty(x["AcknowledgedAt"].S) ? null : DateTimeOffset.Parse(x["AcknowledgedAt"].S, CultureInfo.InvariantCulture));
    private static string E(string value) => Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(value)).TrimEnd('=').Replace('+', '-').Replace('/', '_'); private static AttributeValue S(string value) => new() { S = value };
}
