<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" /></ItemGroup><ItemGroup><ProjectReference Include="../../src/Modules/Pricing/CommerceOS.Pricing.Application/CommerceOS.Pricing.Application.csproj" /><ProjectReference Include="../../src/Modules/Pricing/CommerceOS.Pricing.Domain/CommerceOS.Pricing.Domain.csproj" /><ProjectReference Include="../../src/Modules/Pricing/CommerceOS.Pricing.Infrastructure/CommerceOS.Pricing.Infrastructure.csproj" /></ItemGroup></Project>
