<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CommerceOS.Inventory.Domain/CommerceOS.Inventory.Domain.csproj" /><ProjectReference Include="../CommerceOS.Inventory.Contracts/CommerceOS.Inventory.Contracts.csproj" /><ProjectReference Include="../../SubscriptionBilling/CommerceOS.SubscriptionBilling.Contracts/CommerceOS.SubscriptionBilling.Contracts.csproj" /></ItemGroup></Project>
