<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CommerceOS.OrderOrchestration.Domain/CommerceOS.OrderOrchestration.Domain.csproj" /><ProjectReference Include="../../Inventory/CommerceOS.Inventory.Contracts/CommerceOS.Inventory.Contracts.csproj" /><ProjectReference Include="../../Payments/CommerceOS.Payments.Contracts/CommerceOS.Payments.Contracts.csproj" /><ProjectReference Include="../../Sales/CommerceOS.Sales.Contracts/CommerceOS.Sales.Contracts.csproj" /></ItemGroup></Project>
